### ISSUE TITLE
Error with the script deploy.ps1

### ISSUE THREAD

**Issue by raynaldgirard** [microsoft/botframework-solutions#1365]
## Project
Virtual Assistant Template
**Name**: 

**Language**: 
C#
## Description

Hello,
According to the instructions for the new virtual assistant (https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/virtualassistant.md#download-and-install), I run the scripts .\Deployment\Scripts\ deploy.ps1 and I get an error:

Error: Cannot find module 'C:\Users\myuser\.net\2.1\node_modules\dotnet-2.1-win-x64\'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at ChildProcess.require.spawn.on (C:\Users\myuser\AppData\Roaming\npm\node_modules\botdispatch\node_modules\dotnet-2.1\dist\call.js:39:58)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
## To Reproduce

run deploy.ps1
## Expected behavior

no error

**Comment by gagankohli2000** [comment]
What's the workaround?
