### ISSUE TITLE
Deployment using deploy.ps1 script fails trying to find LUIS files

### ISSUE THREAD

**Issue by BeigeBadger** [microsoft/botframework-solutions#1400]
## Project

**Name**: Skills

**Language**: C#

## Description
Exception thrown when running the `deploy.ps1` script. It is looking for files inside a `Services\` directory of the `Deployment\Scripts\` directory.

## To Reproduce
Follow the `Download and install`, `Create your Skill`, and `Deploy your Skill` steps as detailed [here](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/skill.md).

1. Install Skills template.
2. Create new project using Skills template.
3. Run deploy.ps1 script created by project.
4. Failure during script.

## Expected behavior
Deployment to succeed.

## Screenshots
![https://i.imgur.com/nxRKR7Y.png](https://i.imgur.com/nxRKR7Y.png)

## Additional context
Stack trace:

```
PS C:\Users\mastan\Desktop\MySkill\MySkill\Deployment\Scripts> .\deploy.ps1
? Bot Name (used as default name for resource group and deployed resources): skills-bot
? Azure resource group region: westus
? Password for MSA app registration (must be at least 16 characters long, contain at least 1 special character, and contain at least 1 numeric character): xxxxxxxxxxxxxxxxxxxxxxx
? LUIS Authoring Region (westus, westeurope, or australiaeast): westus
? LUIS Authoring Key (found at https://luis.ai/user/settings): xxxxxxxxxxxxxxxxxxxxxxxxxx
> Creating resource group ...
> Deploying Azure services (this could take a while)...
> Updating appsettings.json ...
> Deploying cognitive models ...
> Parsing General LU file ...

     Update available 1.2.0 -> 1.3.1
     Run npm i -g ludown to update.
> Deploying General LUIS app ...
Generating file C:\Users\mastan\Desktop\MySkill\MySkill\Deployment\Scripts\Services\GeneralLuis.cs that contains class Luis.GeneralLuis.

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\mastan\Desktop\MySkill\MySkill\Deployment\Scripts\Services\GeneralLuis.cs'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at LUISGen.CSharp.Generate(String description, Object app, String className, String space, String outPath) in D:\a\1\s\packages\LUISGen\src\CSharp.cs:line 267
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at LUISGen.Program.Main(String[] args) in D:\a\1\s\packages\LUISGen\src\Program.cs:line 151
> Parsing MySkill LU file ...

     Update available 1.2.0 -> 1.3.1
     Run npm i -g ludown to update.
> Deploying MySkill LUIS app ...
Generating file C:\Users\mastan\Desktop\MySkill\MySkill\Deployment\Scripts\Services\MySkillLuis.cs that contains class Luis.MySkillLuis.

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\mastan\Desktop\MySkill\MySkill\Deployment\Scripts\Services\MySkillLuis.cs'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at LUISGen.CSharp.Generate(String description, Object app, String className, String space, String outPath) in D:\a\1\s\packages\LUISGen\src\CSharp.cs:line 267
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at LUISGen.Program.Main(String[] args) in D:\a\1\s\packages\LUISGen\src\Program.cs:line 151
> Done.
PS C:\Users\mastan\Desktop\MySkill\MySkill\Deployment\Scripts>
```

**Comment by BeigeBadger** [comment]
I found what the issue was - I was calling the `deploy.ps1` script from inside a subfolder, rather than from the root  directory of my skills project.

* Inside `Deployment/Scripts/` the `deploy.ps1` script calls `deploy_cognitive_models.ps1` script.
* When the `deploy_cognitive_models.ps1` script is called the current directory (where ever `deploy.ps1` is being called from) is passed through as the value for the `-outFolder` flag. (line 147)
* The `deploy_cognitive_models.ps1` script expects that the `Services` folder is a directory inside the path provided by the `outFolder` variable. (line 93)
* The `deploy_cognitive_models.ps1` script tried to find the `Services` folder inside `C:\Users\mastan\Desktop\MySkill\MySkill\Deployment\Scripts` (which didn't exist of course).
* Running the script from `C:\Users\mastan\Desktop\MySkill\MySkill` fixed the issue.

This is mentioned in step 1 (in bold) of the Deployment instructions but I didn't realise how important it actually was due to child scripts using relative pathfinding.
