### ISSUE TITLE
Can't run new assistant in emulator

### ISSUE THREAD

**Issue by stepknees** [microsoft/botframework-solutions#1463]
## Project

**Name**: 
Virtual Assistant

**Language**: 
C#

## Description
Cannot run new bot in emulator. I've tried with 3-4 different deployments and had the same behavior. 

## To Reproduce
Follow steps from https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/virtualassistant.md
Download and install
Create your assistant
Deploy your assistant
Run your assistant --> after step 4, bot does not respond (see screenshot)

## Expected behavior
Welcome card shows in emulator & I can interact with assistant. 

## Screenshots

![image](https://user-images.githubusercontent.com/41705920/58725769-d39a1600-8394-11e9-8075-5e9b6a33d420.png)

**Comment by lauren-mills** [comment]
Can you try creating a new bot file through the "create a new bot configuration" link in the emulator? It should ask for the endpoint, appId, and pw (all three are required, and the id a pw should match what's in your app settings)

**Comment by stepknees** [comment]
Should the name be the same as my current project?

**Comment by lauren-mills** [comment]
Name shouldn't matter, its just the name for the connection that shows in the emulator.

**Comment by stepknees** [comment]
Does it matter what path I save it under?

**Comment by lauren-mills** [comment]
No, you can save it anywhere.

**Comment by stepknees** [comment]
Better, maybe – I now at least see something under Endpoint. But I’m getting the “taking longer than usual to connect” message. And I don’t see the development/production under endpoint as in the documentation. Do I need to restart the debugger?
[cid:image001.png@01D517A7.08AB02A0]

**Comment by lauren-mills** [comment]
The dev/prod endpoints are just names for the different connections, the same as the one you added.

Try restarting the conversation using the button at the top, then see if you get anything besides the ngrok messages in the window on the bottom right. If there's nothing there, try sending a message and see what pops up in that window

**Comment by stepknees** [comment]
I’m not getting anything in the log when I try to enter some text; Enter isn’t even working (presumably because I’m not actually connected)

[cid:image001.png@01D517AE.138EED60]

**Comment by stepknees** [comment]
Is it an issue that my emulator & ngrok are listening on a different host than my bot?

From: Stefanie Tomko
Sent: Friday, May 31, 2019 12:41 PM
To: microsoft/botframework-solutions <reply@reply.github.com>; microsoft/botframework-solutions <botframework-solutions@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [microsoft/botframework-solutions] Can't run new assistant in emulator (#1463)

I’m not getting anything in the log when I try to enter some text; Enter isn’t even working (presumably because I’m not actually connected)

[cid:image002.jpg@01D517AE.65E962C0]

**Comment by lauren-mills** [comment]
Can you try reinstalling the emulator? Or try publishing the bot and testing in web chat

**Comment by stepknees** [comment]
Reinstalling the emulator didn’t help. Is there a doc link for the second solution?

Also, just want to note that a .bot file was never created as part of this project – is that normal? (I do have one now, as a result of the “create a new bot config” step you suggested earlier).

**Comment by darrenj** [comment]
It looks like the Emulator as you say is just not working. Not sure which emulator version your on but can you try uninstalling and install 4.3.3 which will rule out any issues with the newer emulator

https://github.com/microsoft/BotFramework-Emulator/releases/tag/v4.3.3

Also, when you start the assistant in Visual Studio do you see the Virtual Assistant page pop-up in the browser. Just double check the localhost:3978 you have in emulator matches what the browser shows and it isn't using a new port.

If you still don't have any joy open up a cmd prompt go to the assistant folder and run 'dotnet run' and see if any exceptions / errors are reported.

**Comment by stepknees** [comment]
Thanks, will try the emulator swap when I get home. I *am* reliably seeing the browser page each time I start the debugger.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by stepknees** [comment]
Earlier emulator didn’t work, but ooh, yeah, getting some dotnet errors:

C:\repos\munich3\munich3\munich3>dotnet run
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\steftom\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:1205 on the IPv4 loopback interface: 'An attempt was made to access a socket in a way forbidden by its access permissions'.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:1205 on the IPv6 loopback interface: 'An attempt was made to access a socket in a way forbidden by its access permissions'.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://localhost:1205. ---> System.AggregateException: One or more errors occurred. (An attempt was made to access a socket in a way forbidden by its access permissions) (An attempt was made to access a socket in a way forbidden by its access permissions) ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

Unhandled Exception: System.IO.IOException: Failed to bind to address http://localhost:1205. ---> System.AggregateException: One or more errors occurred. (An attempt was made to access a socket in a way forbidden by its access permissions) (An attempt was made to access a socket in a way forbidden by its access permissions) ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at munich3.Program.Main(String[] args) in C:\repos\munich3\munich3\munich3\Program.cs:line 13

**Comment by lauren-mills** [comment]
Hm, I've never seen those errors before. Can you try running with IIS instead of dotnet and verify you see the same behavior? 

![image](https://user-images.githubusercontent.com/27976702/58816714-e6a02680-85de-11e9-81a4-627c6f2c7a82.png)

**Comment by jwiley84** [comment]
Just to chime in: "Unable to start Kestrel" means that there was something already running in that port. I frequently run into it, usually when I forget to turn off a bot I'm running.

**Comment by stepknees** [comment]
Sure – how would I do this?

**Comment by stepknees** [comment]
Is there a simple way to clear everything from all ports?

**Comment by darrenj** [comment]
This is weird! Make sure VS is stopped/shut-down, failing that reboot? Maybe some firewall issue or something otherwise?

**Comment by jwiley84** [comment]
Rebooting doesn't always kill IIS (don't ask me why). @stepknees, if you're using windows, you can use the following command in command prompt/command line to see if there's something running on the port you're trying to run your bot on:

`netstat -ano | findstr :1205`

**Comment by darrenj** [comment]
Did some digging - seems to be a variety of VS issues: https://forums.asp.net/t/2144945.aspx?Unable+to+connect+to+web+server+IIS+Express+

Try out netstat and some of the ideas in this article to see if that helps your machine.
