### ISSUE TITLE
Getting exception in QnAMaker.OnQnaResultsAsync

### ISSUE THREAD

**Issue by sysdvj** [microsoft/botframework-solutions#1566]
## Project

**Name**:Microsoft.Bot.Builder.AI.QnA.QnAMaker

**Language**: C#

## Description
   System.ArgumentException: An item with the same key has already been added. Key: question
at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at Microsoft.Bot.Builder.AI.QnA.QnAMaker.FillQnAEventAsync(QueryResult[] queryResults, ITurnContext turnContext, Dictionary2 telemetryProperties, Dictionary2 telemetryMetrics, CancellationToken cancellationToken) at Microsoft.Bot.Builder.AI.QnA.QnAMaker.OnQnaResultsAsync(QueryResult[] queryResults, ITurnContext turnContext, Dictionary2 telemetryProperties, Dictionary2 telemetryMetrics, CancellationToken cancellationToken) at Microsoft.Bot.Builder.AI.QnA.QnAMaker.GetAnswersAsync(ITurnContext turnContext, QnAMakerOptions options, Dictionary2 telemetryProperties, Dictionary`2 telemetryMetrics)

## To Reproduce
In QnAMaker
When we have LogPersonalInformation set to true
And QnA app does not returns any QueryResult
Then it is trying to add same key two time for event logging and below exception occurred.

## Expected behavior
It should not add duplicate key named "question" and should not throw exception.

## Screenshots
NA

**Comment by darrenj** [comment]
Should be resolved by the most recent BF SDK version (4.4.5) and PR is here: https://github.com/microsoft/botbuilder-dotnet/pull/1899

Let us know if it doesn't resolve your issue.

**Comment by FreddyAyala** [comment]
Hello, in my case I've two Knowledge Bases, with one of them I've the exception:

An item with the same key has already been added. Key: question

With the following stack trace:

 at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)\n   at Microsoft.Bot.Builder.AI.QnA.QnAMaker.FillQnAEventAsync(QueryResult[] queryResults, ITurnContext turnContext, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.AI.QnA\\QnAMaker.cs:line 256\n   at Microsoft.Bot.Builder.AI.QnA.QnAMaker.OnQnaResultsAsync(QueryResult[] queryResults, ITurnContext turnContext, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.AI.QnA\\QnAMaker.cs:line 202\n   at Microsoft.Bot.Builder.AI.QnA.QnAMaker.GetAnswersAsync(ITurnContext turnContext, QnAMakerOptions options, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.AI.QnA\\QnAMaker.cs:line 192\n   at Dave.Chatbot.Core.Dialogs.MainDialog.CheckProceduresKB(DialogContext dc, CognitiveModelSet cognitiveModels) in /Users/frayala/Documents/Dave-Platform/dave-virtual-assistant/Dave.Bot.Core/Dialogs/MainDialog.cs:line 157\n   at Dave.Chatbot.Core.Dialogs.MainDialog.RouteAsync(DialogContext dc, CancellationToken cancellationToken) in /Users/frayala/Documents/Dave-Platform/dave-virtual-assistant/Dave.Bot.Core/Dialogs/MainDialog.cs:line 78\n   at Microsoft.Bot.Builder.Solutions.Dialogs.RouterDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.Dialogs\\ComponentDialog.cs:line 86\n   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.Dialogs\\DialogContext.cs:line 160\n   at Dave.Chatbot.Core.Bots.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in /Users/frayala/Documents/Dave-Platform/dave-virtual-assistant/Dave.Bot.Core/Bots/DialogBot.cs:line 43\n   at Microsoft.Bot.Builder.AutoSaveStateMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\AutoSaveStateMiddleware.cs:line 60\n   at Microsoft.Bot.Builder.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\ShowTypingMiddleware.cs:line 71\n   at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\TelemetryLoggerMiddleware.cs:line 109\n   at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\TranscriptLoggerMiddleware.cs:line 108\n   at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\BotFrameworkAdapter.cs:line 995\n   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\MiddlewareSet.cs:line 55\n   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\BotAdapter.cs:line 167

I've the following versions:


    <PackageReference Include="Microsoft.Bot.Builder" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Builder.AI.Luis" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Builder.AI.QnA" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Builder.ApplicationInsights" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Builder.Azure" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.ApplicationInsights.Core" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Builder.Skills" Version="4.4.4.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Solutions" Version="4.4.4.1" />
    <PackageReference Include="Microsoft.Bot.Builder.TemplateManager" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Configuration" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Connector" Version="4.4.5" />
    <PackageReference Include="Microsoft.Bot.Schema" Version="4.4.5" />

The fix doesn't seem to be working.

**Comment by stevengum** [comment]
This has been fixed via microsoft/botbuilder-dotnet#1899 against `master`, the wrong key was being used. `QnATelemetryConstants.MatchedQuestionProperty` was supposed to have been used instead of `QnATelemetryConstants.QuestionProperty`

`master` is available as a [nightly build via MyGet](https://github.com/microsoft/botbuilder-dotnet/blob/master/UsingMyGet.md), otherwise we'll be cutting 4.5 which will have this release in mid-July.
