### ISSUE TITLE
Not able to access skill which is an existing SDK v4 bot from the virtual assistant 

### ISSUE THREAD

**Issue by Basavarajsk** [microsoft/botframework-solutions#1679]
I converted the existing SDK v4 bot to skill which is in node js. Connected this bot to virtual assistant using localManifest.
When i tried to contact this skill from the virtual assistant, skill is not getting any request from the VA. I could see in VA it triggered the skill dailog.

**Comment by darrenj** [comment]
Hi,

Can you provide some more information as to your scenario? 

- Are you using a C# based Virtual Assistant or Typescript
- Skill is in nodeJS/Typescript?
- Did you add the Skill to your VA bot using the botskills tool?
- When using the emulator to talk to VA, when you try to trigger the Skill do you see any messages/warnings in the debug pane?
- Any exceptions in AppInsights you can see?

**Comment by Basavarajsk** [comment]
Hi,
Below are the information.

- My virtual assistant is Typescript

- Skill is in nodejs. Converted the existing SDK v4 bot as skill.

- Added skill to VA bot using localManifest, as I am getting an error 404 source not found with remotemanifest. Below is the command I am using for remote manifest connection
`botskills connect --botName "zbrvirtualassistantbot" --remoteManifest "https://testsdk4skill.azurewebsites.net/api/skill/manifest" --ts`

- No I am not getting an warnings or errors but bot is posting typing activity only.

- Yes, I could see below exceptions in skill's appInsights
1. TypeError:
   at CustomSkillAdapter.processActivity (at CustomSkillAdapter.processActivity (D:\home\site\wwwroot\node_modules\botbuilder-skills\lib\http\skillHttpBotAdapter.js:55:30)at CustomSkillAdapter.processActivity (D:\home\site\wwwroot\node_modules\botbuilder-skills\lib\http\skillHttpBotAdapter.js:55:30): D:\home\site\wwwroot\node_modules\botbuilder-skills\lib\http\skillHttpBotAdapter.jsat CustomSkillAdapter.processActivity (D:\home\site\wwwroot\node_modules\botbuilder-skills\lib\http\skillHttpBotAdapter.js:55:30): 55)
   at SkillHttpAdapter.processActivity (at SkillHttpAdapter.processActivity (D:\home\site\wwwroot\node_modules\botbuilder-skills\lib\http\skillHttpAdapter.js:41:54)at SkillHttpAdapter.processActivity (D:\home\site\wwwroot\node_modules\botbuilder-skills\lib\http\skillHttpAdapter.js:41:54): D:\home\site\wwwroot\node_modules\botbuilder-skills\lib\http\skillHttpAdapter.jsat SkillHttpAdapter.processActivity (D:\home\site\wwwroot\node_modules\botbuilder-skills\lib\http\skillHttpAdapter.js:41:54): 41)
   at process._tickCallback (at process._tickCallback (internal/process/next_tick.js:68:7)at process._tickCallback (internal/process/next_tick.js:68:7): internal/process/next_tick.jsat process._tickCallback (internal/process/next_tick.js:68:7): 68)

2. Microsoft.Bot.Schema.BotException:
   at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext (Microsoft.Bot.Base.ChannelConnector, Version=3.2.3.3, Culture=neutral, PublicKeyToken=null)
Inner exception System.Exception handled at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext:
   at Microsoft.Bot.ChannelConnector.BotAPI.ThrowOnFailedStatusCode (Microsoft.Bot.Base.ChannelConnector, Version=3.2.3.3, Culture=neutral, PublicKeyToken=null)
   at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext (Microsoft.Bot.Base.ChannelConnector, Version=3.2.3.3, Culture=neutral, PublicKeyToken=null)

**Comment by dfavretto** [comment]
Hi @Basavarajsk,
 
First of all, we would like to understand the reason of the error using `botskills` tool. The tool is getting an *error 404* and that's because your `remoteManifest` doesn't exist or the tool can't reach to it.
•	Are you using the *latest version* ([_v1.0.7_](https://www.npmjs.com/package/botskills)) of the botskills tool?
•	Can you execute again the connect command with `--verbose` argument and send us the output of the process?
 
About the connection of the *Virtual Assistant* and the *Skill* using `localManifest`:
•	Can you check if the connection was successful? You can check this by seeing if the Virtual Assistant's Dispatch contains your skill information, like the path to your Skill's LU file.
•	As @darrenj asked, when sending a message in the Bot Framework Emulator, do you see the following message in the lateral pane of the emulator?
```
--> Forwarding your utterance to the <YOUR_SKILL_NAME> skill.
```

**Comment by Basavarajsk** [comment]
Hi @dfavretto,

- PFA 

![image](https://user-images.githubusercontent.com/24410864/60803543-153e8d80-a199-11e9-81f8-a9c9b7ff6d6b.png)

- Yes, i can see the my skill utterances in dispatcher module of the VA.

- Yes I can see the message as  "Handing off to the <SKILL_NAME> skill.

![image](https://user-images.githubusercontent.com/24410864/60806984-1627ed00-a1a2-11e9-8847-7b9141017bc2.png)

**Comment by Batta32** [comment]
Hi @Basavarajsk,

The manifest that you are providing to the botskills tool is a resource that the tool cannot find. Please, check that your remote manifest is available, valid and if the index file of your skill contains the endpoint of `/api/skill/manifest` like the ones that are generated using the `generator-botbuilder-assistant` or the [sample-skill](https://github.com/microsoft/botframework-solutions/blob/d959aafc19da5a3667e3bfe04eece734ceca2b92/templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/index.ts#L199)

Regarding to the connection of the skill to the assistant, can you try to connect the [sample-skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill) of the repo, and test the connection between them? So we can narrow the possible issues to the Skill, discarding any other possibilities.

**Comment by darrenj** [comment]
@Basavarajsk  Any update on this?

**Comment by darrenj** [comment]
PR for the JS StreamingExtensions library is here FYI: https://github.com/microsoft/botbuilder-js/pull/1081

**Comment by darrenj** [comment]
Work is tracked [here](https://github.com/microsoft/botframework-solutions/issues/2489) and targeting next release. Please keep an eye on the issue and we'll point at daily builds when available.
