### ISSUE TITLE
Luisgen not adding new KB to DispatchLuis.ts on mac

### ISSUE THREAD

**Issue by mbwatty** [microsoft/botframework-solutions#2122]
#### What project is affected?
luisgen

#### What language is this in?
Typescript

#### What happens?
When trying to add a new knowledgebase to the dispatch model luisgen generates an empty DispatchLuis.ts file. 

#### What are the steps to reproduce this issue?
I initially had issues getting luisgen working on my mac but this solved it [2075](https://github.com/microsoft/botframework-solutions/issues/2075). 
After adding the new KB to dispatch and refreshing dispatch successfully (I think) I then tried to update luisgen with 
`luisgen "deployment/resources/Dispatch/TheSafetyBoten_Dispatch.dispatch" -ts "DispatchLuis" -o "src/services"`

#### What were you expecting to happen?
An updated DispatchLuis.ts file with the new KB intent.

#### Can you share any logs, error output, etc.?
```
Generating file src/services/DispatchLuis.ts that contains interface DispatchLuis.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at LUISGen.Typescript.Intents(Object app, Writer w) in D:\a\1\s\packages\LUISGen\src\Typescript.cs:line 31
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at LUISGen.Typescript.Generate(String description, Object app, String className, String outPath) in D:\a\1\s\packages\LUISGen\src\Typescript.cs:line 205
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid5[T0,T1,T2,T3,T4](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at LUISGen.Program.Main(String[] args) in D:\a\1\s\packages\LUISGen\src\Program.cs:line 179
Abort trap: 6
```

**Comment by cleemullins** [comment]
Hi @mbwatty, this looks like a possible bug in LuisGen. We're currently in-process making changes to that command line tool; that work is being driven by @axelsrz who should be able to pickup this fix as part of the next major release (tentatively schedule for 4.6 in the Oct 31 time frame).

**Comment by cleemullins** [comment]
@Bata32, I see you took this - do you have plans to update the Luisgen C# code to fix? If so, please work with @axelsrz to sync on the fix and a release plan for the fix.
