### ISSUE TITLE
Unable to deploy Virtual Assistant

### ISSUE THREAD

**Issue by hammocktester** [microsoft/botframework-solutions#2225]
**Project**
Name: Virtual Assistant

Language: C#

**Description**
I'm trying to deploy the virtual assistant via the guide here - https://microsoft.github.io/botframework-solutions/tutorials/csharp/create-assistant/4_provision_your_azure_resources/

I already have an RG setup along with an appid and password

**To Reproduce**
Run PowerShell Core (pwsh.exe) and change directory to the project directory of your assistant/skill.
Run the following command: .\Deployment\Scripts\deploy.ps1 and I get the following error - 

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'P:\\\\'

Appears to fail at this bit of the powershell

if ($parametersFile) {
	Write-Host "> Validating Azure deployment ..."
	$validation = az group deployment validate `
		--resource-group $resourcegroup `
		--template-file "$(Join-Path $PSScriptRoot '..' 'Resources' 'template.json')" `
		--parameters "@$($parametersFile)" `
		--parameters name=$name microsoftAppId=$appId microsoftAppPassword="`"$($appPassword)`"" `
        --output json

**Expected behavior**
The deployment should occur.

**Log**

> Creating resource group ...
> Validating Azure deployment ...
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli\azure\cli\__main__.py", line 33, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\__init__.py", line 539, in get_default_cli
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\azlogging.py", line 30, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\commands\__init__.py", line 28, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\extension\__init__.py", line 16, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\config.py", line 39, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\util.py", line 108, in ensure_dir
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\util.py", line 105, in ensure_dir
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'P:\\\\'
> finished validation

**Comment by Robotbae** [comment]
How'd you fix it @hammocktester I am facing the same issue
