### ISSUE TITLE
Update Activity from the VA 

### ISSUE THREAD

**Issue by tommyJimmy87** [microsoft/botframework-solutions#2388]
#### What project is affected?
Skill
#### What language is this in?
Typescript
#### What happens?

I have a virtual Assistant connected to one skill, the skill is using the updateActivity function to render and update some adaptive cards to be shown in MS Teams. The UpdateActivity work well if I run the application directly from the skill, but as soon as I try it from the Virtual Assistant (this means that the VA routes the call to the skill) it crash with this error : `Error: Http Request/Response model doesn't support UpdateActivityAsync call!`

#### Can you share any logs, error output, etc.?

``` Error: Http Request/Response model doesn't support UpdateActivityAsync call!
    at CalendarSkillAdapter.updateActivity (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-skills/lib/http/skillHttpBotAdapter.js:49:15)
    at emit (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:262:79)
    at emitNext (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:451:40)
    at Promise.resolve.list.(anonymous function) (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:449:72)
    at Array.context.onUpdateActivity (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/transcriptLogger.js:50:36)
    at emitNext (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:449:51)
    at Promise.resolve.list.(anonymous function) (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:449:72)
    at Array.context.onUpdateActivity (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/telemetryLoggerMiddleware.js:60:36)
    at emitNext (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:449:51)
    at Proxy.emit (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:457:16)
Error: Http Request/Response model doesn't support UpdateActivityAsync call!
    at CalendarSkillAdapter.updateActivity (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-skills/lib/http/skillHttpBotAdapter.js:49:15)
    at emit (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:262:79)
    at emitNext (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:451:40)
    at Promise.resolve.list.(anonymous function) (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:449:72)
    at Array.context.onUpdateActivity (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/transcriptLogger.js:50:36)
    at emitNext (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:449:51)
    at Promise.resolve.list.(anonymous function) (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:449:72)
    at Array.context.onUpdateActivity (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/telemetryLoggerMiddleware.js:60:36)
    at emitNext (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:449:51)
    at Proxy.emit (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/botbuilder-core/lib/turnContext.js:457:16)
Trace
    at Console.originalConsole.(anonymous function) [as trace] (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/node_modules/diagnostic-channel-publishers/dist/src/console.pub.js:42:39)
    at DialogBot.turn (/Users/user/Desktop/project/GitLab/src/wa-meeting-skill/lib/bots/dialogBot.js:56:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by darrenj** [comment]
Hi Tommy,

Thanks for raising the issue, yes - this (was/is) a limitation of using HTTP for Skill invocation and is one of the main reasons we had to move to the websockets approach for skill invocation using the [Streaming Extensions](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-streaming-extensions).

We completed the C# work for this at Build and a couple of weeks ago got the js version bits which we are actively integrating as we speak. This, like with the c# variant will enable you to use update activities especially for Teams scenarios as you highlight. 

Working on a timescale to have the bits this week, will leave this open so we can provide an update to a daily build that you can test in the not too distant future.

**Comment by tommyJimmy87** [comment]
Hi @darrenj, 
Thanks for the update. Would be great if you could keep me update on the Typescript enablement.
:)

**Comment by tommyJimmy87** [comment]
Hi @darrenj,

Do you know if the library has been released ?

**Comment by darrenj** [comment]
I'll update this issue once we have the changes integrated.

**Comment by darrenj** [comment]
Work is tracked [here](https://github.com/microsoft/botframework-solutions/issues/2489) and targeting next release. Please keep an eye on the issue and we'll point at daily builds when available.

**Comment by tommyJimmy87** [comment]
@darrenj  Cool thanks.
