### ISSUE TITLE
Latest sdk 4.5.4 gives error when debugging locally

### ISSUE THREAD

**Issue by neetgupta7** [microsoft/botframework-solutions#2482]
I upgraded Microsoft.Bot.Builder.Skills to 4.5.4 and now when i debug my skill locally with simple echo dialog with blank microsoftAppId and password i get below error.

### System.ArgumentNullException: Value cannot be null.
Parameter name: microsoftAppId
   at Microsoft.Bot.Builder.Skills.Auth.MsJWTAuthenticationProvider..ctor(String microsoftAppId, String openIdMetadataUrl) in D:\a\1\s\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\Auth\MsJWTAuthenticationProvider.cs:line 20
   at Microsoft.Bot.Builder.Skills.SkillWebSocketAdapter..ctor(SkillWebSocketBotAdapter skillWebSocketBotAdapter, BotSettingsBase botSettingsBase, IWhitelistAuthenticationProvider whitelistAuthenticationProvider, IBotTelemetryClient botTelemetryClient) in D:\a\1\s\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\SkillWebSocketAdapter.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetrySaveBodyASPMiddleware.Invoke(HttpContext httpContext) in d:\a\1\s\libraries\integration\Microsoft.Bot.Builder.Integration.ApplicationInsights.Core\TelemetrySaveBodyASPMiddleware.cs:line 55
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by darrenj** [comment]
@neetgupta7 - We'll take a look. Out of interest, is there a reason you cannot have AppId and Secrets populated on the Bot/Skill which is the usual approach. These AppIds are used as part of the security model - will look into a "opt out" option but would be good to understand background if possible.

Thanks

**Comment by neetgupta7** [comment]
@darrenj Thanks for your response. Its just about local debugging when developer starts a bot and havent created any azure resources and testing through simulator.

**Comment by lzc850612** [comment]
@neetgupta7 thanks for raising this issue. In 4.5.4 we have improvements over security authentication for the skill invocation. One of those improvements is for the skill to be able to verify the S2S token that's sent alongside the call from VA. In order to be able to validate the token, the skill needs to have proper identity and that's supported by MicrosoftAppId and MicrosoftAppPassword. Without having them the S2S authentication wouldn't be able to pass. We decided that it's necessary for the authentication to be on by default to ensure the security of the invocation so that the skill won't be susceptible to spamming attacks. The BotFramework SDK as well as the deployment scripts out of box of the SkillTemplate allow easy provisioning of MicrosoftAppId and password to ensure easy setup for skill to take advantage of the security model. Please follow the skill documentation https://microsoft.github.io/botframework-solutions/tutorials/csharp/create-skill/1_intro/ to create all the resources needed including the MicrosoftAppId and password.

Thanks.

**Comment by darrenj** [comment]
We are aware that some customers environments restrict the ability to create AppIds so you may need to approach your administrator and ask for a block of AppIds to use for testing.

If we had a way to disable security, you would then run into other limitations such as not being able to use Authentication (OAuthPrompt) within your skill, etc.

**Comment by darrenj** [comment]
Any update @neetgupta7 ?

**Comment by lauren-mills** [comment]
Closing due to inactivity. Please reopen as needed.

**Comment by sharath-collab** [comment]
Hi,

Even we are facing the same issue when try to debug the latest skill sample project with out specifying app id & app password. Facing below issue.

Ideally before creating azure resources in our customer environment, we have to be sure it works using bot emulator.
In earlier versions we used to test it by leaving the app id & app secret blank. Kindly help here

ArgumentNullException: Value cannot be null.
Parameter name: microsoftAppId

Microsoft.Bot.Builder.Skills.Auth.MsJWTAuthenticationProvider..ctor(string microsoftAppId, string openIdMetadataUrl) in MsJWTAuthenticationProvider.cs, line 20
