### ISSUE TITLE
Websocket error when debugging VA and skill

### ISSUE THREAD

**Issue by neetgupta7** [microsoft/botframework-solutions#2483]
I have a VA and multiple skills deployed to Azure. I am trying to locally test them using ngrok. So i have VA and 2 skills hosted locally and exposed via ngrok. I have updated skills.json with ngrok url of 2 skills for their end points and also updated the the end point of VA.

Now this set up used to work earlier but after i updated my packages to 4.5.3 i started getting below error-

![image](https://user-images.githubusercontent.com/28854156/66312990-34cb8a80-e92f-11e9-89dc-aae14aa1db38.png)

   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.Bot.StreamingExtensions.Transport.WebSockets.WebSocketClient.ConnectAsync(IDictionary`2 requestHeaders)
   at Microsoft.Bot.Builder.Skills.SkillWebSocketTransport.ForwardToSkillAsync(SkillManifest skillManifest, IServiceClientCredentials serviceClientCredentials, ITurnContext turnContext, Activity activity, Action`1 tokenRequestHandler, Action`1 fallbackHandler) in D:\a\1\s\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\SkillWebSocketTransport.cs:line 58
   at Microsoft.Bot.Builder.Skills.SkillDialog.ForwardToSkillAsync(DialogContext innerDc, Activity activity) in D:\a\1\s\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\SkillDialog.cs:line 321
   at Microsoft.Bot.Builder.Skills.SkillDialog.ForwardToSkillAsync(DialogContext innerDc, Activity activity) in D:\a\1\s\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\SkillDialog.cs:line 391
   at Microsoft.Bot.Builder.Skills.SkillDialog.OnBeginDialogAsync(DialogContext innerDc, Object options, CancellationToken cancellationToken) in D:\a\1\s\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\SkillDialog.cs:line 215
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.BeginDialogAsync(DialogContext outerDc, Object options, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\ComponentDialog.cs:line 60
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 113
   at ***.MainDialog.RouteAsync(DialogContext dc, CancellationToken cancellationToken) in D:\***\src\VirtualAssistant\Dialogs\MainDialog.cs:line 139
   at Microsoft.Bot.Builder.Solutions.Dialogs.RouterDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken) in D:\a\1\s\lib\csharp\microsoft.bot.builder.solutions\microsoft.bot.builder.solutions\Dialogs\RouterDialog.cs:line 63
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\ComponentDialog.cs:line 84
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 160
   at ***.Bots.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in D:\***\src\VirtualAssistant\Bots\DialogBot.cs:line 43
   at ***.Bot.Security.ClaimsPrincipalBotDecorator.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in D:\***\src\VirtualAssistant.Bot.Common\Bot\Security\BotClaimsPrincipalDecorator.cs:line 43
   at Microsoft.Bot.Builder.AutoSaveStateMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\AutoSaveStateMiddleware.cs:line 60
   at Microsoft.Bot.Builder.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in D:\a\1\s\lib\csharp\microsoft.bot.builder.solutions\microsoft.bot.builder.solutions\Middleware\EventDebuggerMiddleware.cs:line 60
   at Microsoft.Bot.Builder.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken) in D:\a\1\s\lib\csharp\microsoft.bot.builder.solutions\microsoft.bot.builder.solutions\Middleware\SetLocaleMiddleware.cs:line 29
   at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\ShowTypingMiddleware.cs:line 71
   at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\TelemetryLoggerMiddleware.cs:line 109
   at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\TranscriptLoggerMiddleware.cs:line 108
   at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 1051
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167

**Comment by lzc850612** [comment]
Hi neetgupta7,

Thanks for raising this issue and let's get some more information. 

1. what is the version of the microsoft.bot.builder.skills library you were using before that worked?
2. when you have upgraded to 4.5.3 for the lib, is there any exceptions when you look at the Output window for both the VA and the skills running locally?

**Comment by darrenj** [comment]
Any update @neetgupta7?

**Comment by lauren-mills** [comment]
Closing due to inactivity. Please reopen as needed.
