### ISSUE TITLE
Inconsistent bot response in Teams channel

### ISSUE THREAD

**Issue by YammanureSreekanth** [microsoft/botframework-solutions#2722]
* When we say **'hi'**, it should reply the welcome card as per our flow (which is working fine in Webchat channel). But it's giving different cards and seems this is getting cached.

Need your assistance on this.

Please let me know if you need more details on this.

Thanks,
Sreekanth

**Comment by lauren-mills** [comment]
@SreekanthOAuth - We have updated our VA template and libs to support intro message and auth in Teams. Please try updating your project and let us know if the issues are resolved.

**Comment by YammanureSreekanth** [comment]
@lauren-mills  - Thanks for the update.

We have been working on Virtual Assistant since from 5 months. So we have a lot of updates to our VA.
It would be a great help if you can give details on what are the major changes happened to make it work.

We are on Typescript

Thanks,
Sreekanth

**Comment by lauren-mills** [comment]
The updates have been made to the C# template, and should be coming to the typescript template soon. The primary changes were to inherit from the TeamsActivityHandler instead of IBot in the DialogBot class. Here is the file in the C# template, and I believe the TypeScript changes should be the same, but let me know if you run into any issues. https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Bots/DefaultActivityHandler.cs

**Comment by YammanureSreekanth** [comment]
Thanks for the update. We will try and get back to you.

Thanks,
Sreekanth

**Comment by YammanureSreekanth** [comment]
We see the DialogBot is extending from ActivityHandler in current virtual assistant.

https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/bots/dialogBot.ts

We don't find 'TeamsActivityHandler' in '**botbuilder**' npm package.

And, below are few more queries
Is this change only for Virtual Assistant or even for skill as well?
This change is not specific to Teams channel, right? If not, how does this impact/works on other channels?

Please let me know if you need any further details on it.

Thanks,
Sreekanth

**Comment by lauren-mills** [comment]
I can see the teamsActivityHandler in the source for botbuilder-js [here](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder/src). Can you make sure you're on version 4.6?

This change should be made in any bot that will be directly accessed via teams. If you plan on exposing your skill directly (rather than through a VA) you would also need this change to enable Teams activity handling. Otherwise, it is not critical to update the skill project.

Also, despite the name, this activity handler will work for all the other channels in addition to Teams. It just adds additional Teams handling.

**Comment by YammanureSreekanth** [comment]
After installing the latest version, seeing exceptions while starting the server. Could you please suggest us on this.
[errors.txt](https://github.com/microsoft/botframework-solutions/files/3900886/errors.txt)

**Comment by lauren-mills** [comment]
@Batta32 - can you take a look at the error log above and give any advice?

**Comment by Batta32** [comment]
Hi @SreekanthOAuth, we came up with some questions related to the installation you made.

1. Can you verify that you installed the following version?
	a. `botbuilder` libraries - [4.6.2](https://www.npmjs.com/package/botbuilder/v/4.6.2)
	b. `botbuilder-skills` - [4.4.9](https://www.npmjs.com/package/botbuilder-skills/v/4.4.9)
	c. `botbuilder-solutions` - [4.4.9](https://www.npmjs.com/package/botbuilder-solutions/v/4.4.9)
1. Have you removed the `package-lock.json` file and the `node_modules` folder before the installation? If not, please remove them, update the libraries version to the latest and execute the installation again.

The issue might be related to a **disparity** of `botbuilder` version inside the Virtual Assistant against to the ones of `botbuilder-solutions` and `botbuilder-skills`.
- botbuilder-skills@4.4.8 uses botbuilder@4.5.3
- botbuilder-solutions@4.4.8 uses botbuilder@4.5.3
- botbuilder-skills@4.4.9 uses botbuilder@4.6.2
- botbuilder-solutions@4.4.9 uses botbuilder@4.6.2
	
We will be attentive to your answer 😊.

**Comment by YammanureSreekanth** [comment]
@Batta32 , Thanks for details.

Today, we have tried these and not seeing errors while starting the server. But we are seeing an issue when we request the utterance in teams channel,

And getting staus code as 501 which means **NOT_IMPLEMENTED**

`Error:
   at DefaultAdapter.<anonymous> (at DefaultAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:640:27)at DefaultAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:640:27): D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.jsat DefaultAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:640:27): 640)
   at fulfilled (at fulfilled (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:11:58)at fulfilled (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:11:58): D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.jsat fulfilled (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:11:58): 11)
   at process._tickCallback (at process._tickCallback (internal/process/next_tick.js:68:7)at process._tickCallback (internal/process/next_tick.js:68:7): internal/process/next_tick.jsat process._tickCallback (internal/process/next_tick.js:68:7): 68)`

Based on these logs and our analysis, seems the Activity Type is going as **Invoke** and inside below code, it's getting failed.

`processActivity(req, res, logic) {
        return __awaiter(this, void 0, void 0, function* () {
            let body;
            let status;
            let processError;
            try {
                // Parse body of request
                status = 400;
                const request = yield parseRequest(req);
                // Authenticate the incoming request
                status = 401;
                const authHeader = req.headers.authorization || req.headers.Authorization || '';
                yield this.authenticateRequest(request, authHeader);
                // Process received activity
                status = 500;
                const context = this.createContext(request);
                context.turnState.set(botbuilder_core_1.BotCallbackHandlerKey, logic);
                yield this.runMiddleware(context, logic);
                // Retrieve cached invoke response.
                if (request.type === botbuilder_core_1.ActivityTypes.Invoke) {
                    const invokeResponse = context.turnState.get(exports.INVOKE_RESPONSE_KEY);
                    **if (invokeResponse && invokeResponse.value) {**
                        const value = invokeResponse.value;
                        status = value.status;
                        body = value.body;
                    }
                    **else {
                        status = 501;
                    }**
                }
                else {
                    status = 200;
                }
            }
            catch (err) {
                // Catch the error to try and throw the stacktrace out of processActivity()
                processError = err;
                body = err.toString();
            }
            // Return status 
            res.status(status);
            if (body) {
                res.send(body);
            }
            res.end();
            // Check for an error
            if (status >= 400) {
                if (processError && processError.stack) {
                    throw new Error(`BotFrameworkAdapter.processActivity(): ${status} ERROR\n ${processError.stack}`);
                }
                else {
                    throw new Error(`BotFrameworkAdapter.processActivity(): ${status} ERROR`);
                }
            }
        });
    }`

Could you please suggest us on this.

Thanks,
Sreekanth

**Comment by Batta32** [comment]
Hi @SreekanthOAuth, we managed to reproduce the scenario of the end of conversation.

We noticed that the conversation **is not ending** when an error is raised in the Skill's side, in C# and in TypeScript as well. We are analyzing some alternatives and we will get back to you later 😊.

Also, we noticed that this scenario is happening regardless the `showTypingMiddleware` is commented or not. Can you verify this?

**Comment by Batta32** [comment]
Hi @SreekanthOAuth, we came up with some questions to figure out what's wrong.

1. Can you share the entire log file with the errors if it's available?
1. Can you verify if this issue happens using the Emulator?
1. Does this happens for every intent that you want to execute or for a specific one? (e.g an intent which requires authentication access)
1. Is your [dialogBot](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/bots/dialogBot.ts#L19) extending to [ActivityHandler](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/activityHandler.ts) or [TeamsActivityHandler](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/teamsActivityHandler.ts)?

**Comment by YammanureSreekanth** [comment]
Hi @Batta32 ,  please find the answers below

1.Can you share the entire log file with the errors if it's available?
**_In log stream seeing below response_**

![image](https://user-images.githubusercontent.com/24246902/70295824-530a1580-180e-11ea-8ea8-987d9b0b78a9.png)



2.Can you verify if this issue happens using the Emulator? 
  **_Yes, it's working fine in Emulator and Webchat channels_**
3.Does this happens for every intent that you want to execute or for a specific one? (e.g an intent which requires authentication access)
**_The first step in our bot is Sign in. Since it's getting failed first step not sure whether this case is same for all or not.  But we will get back to you on this._**
4.Is your dialogBot extending to ActivityHandler or TeamsActivityHandler?
**_It's extending  with TeamsActivityHandler_**

**Comment by Batta32** [comment]
Hi @SreekanthOAuth, sorry for the delay. We managed to reproduce your scenario which we **solved** overriding the method `handleTeamsSigninVerifyState` on the [DialogBot](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/bots/dialogBot.ts#L19) which extends `TeamsActivityHandler`. As you can see in [TeamsActivityHandler](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/teamsActivityHandler.ts#L35), it contains some methods that are not implemented, which we should override.

With this said, could you tell us if you are implementing the method `handleTeamsSigninVerifyState` in the class that implements `TeamsActivityHandler`? If not, you can use the code of below:

```TypeScript
public async handleTeamsSigninVerifyState(context: TurnContext, state: SigninStateVerificationQuery): Promise<void> {
    await this.dialog.run(context, this.state);
}
```

To accomplish this, we followed these **steps** using the [Virtual Assistant Sample](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant):
1. Change [`DialogBot.ts`](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/bots/dialogBot.ts) to extend `TeamsActivityHandler`
2. On `DialogBot`, implement the method `handleTeamsSigninVerifyState` overriden as shown in the [Teams Auth Sample](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/46.teams-auth/bots/teamsBot.js#L28)
3. Run the Virtual Assistant Sample in Teams and make sure that it is receiving the request type `Invoke` in [botFrameworkAdapter](https://github.com/microsoft/botbuilder-js/blob/4.future/libraries/botbuilder/src/botFrameworkAdapter.ts#L741).
**Note:** This was important as the type `Invoke` is received only when logging in from a Teams channel.

The overridden `handleTeamsSigninVerifyState` is called after signing in in Teams, instead of `await bot.run(turnContext);` found in `index.ts`.
If the method is not implemented, it would default to use the server post in the index, and it causes the `context.turnState.get()` in [botFrameworkAdapter](https://github.com/microsoft/botbuilder-js/blob/4.future/libraries/botbuilder/src/botFrameworkAdapter.ts#L742) to return an `invokeResponse` with status `501`, which in turn is used to create and send a response with said status.

### Additional Context
  - [NodeJS Sample #46: Teams Auth](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/46.teams-auth)
  - [NodeJS Sample #57: Teans Conversation Bot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/57.teams-conversation-bot)
  - [Add authentication to your bot via Azure Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp)
- [Virtual Assistant: Extend to Microsoft Teams](https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-teams/1-intro/)

_Scenario reproduced_
![image](https://user-images.githubusercontent.com/11904023/71017749-db719b80-20d5-11ea-8327-df5f8b4c1922.png)

We hope this helps you 😊.

**Comment by YammanureSreekanth** [comment]
Hi @Batta32 , thanks for the update.

I have tried to adding these changes but getting some errors

After adding changes, dialogBot.ts file  

`

import {
    ActivityHandler,
    BotTelemetryClient,
    ConversationState,
    EndOfConversationCodes,
    Severity,
    SigninStateVerificationQuery,
    TeamsActivityHandler,
    TurnContext, 
    StatePropertyAccessor} from 'botbuilder';
import {
    Dialog,
    DialogContext,
    DialogSet,
    DialogState,
    DialogTurnResult } from 'botbuilder-dialogs';

export class DialogBot<T extends Dialog> extends TeamsActivityHandler {
    private readonly telemetryClient: BotTelemetryClient;
    private readonly solutionName: string = 'Ecolab Virtual Assistance';
    private readonly rootDialogId: string;
    private readonly dialogs: DialogSet;
    private readonly dialog: Dialog;
    private readonly dialogState: StatePropertyAccessor<DialogState>;

    constructor(
        conversationState: ConversationState,
        telemetryClient: BotTelemetryClient,
        dialog: T) {
        super();

        this.rootDialogId = dialog.id;
        this.telemetryClient = telemetryClient;
        this.dialogState = conversationState.createProperty<DialogState>(this.solutionName); // new one
        this.dialogs = new DialogSet(this.dialogState);
        this.dialogs.add(dialog);
        this.onTurn(this.turn.bind(this));
        this.dialog = dialog; // new one
    }

    //tslint:disable-next-line: no-any
    public async turn(turnContext: TurnContext, next: () => Promise<void>): Promise<any> {
        // Client notifying this bot took to long to respond (timed out)
        if (turnContext.activity.code === EndOfConversationCodes.BotTimedOut) {
            this.telemetryClient.trackTrace({
                message: `Timeout in ${ turnContext.activity.channelId } channel: Bot took too long to respond`,
                severityLevel: Severity.Information
            });

            return;
        }

        const dc: DialogContext = await this.dialogs.createContext(turnContext);

        if (dc.activeDialog !== undefined) {
            const result: DialogTurnResult = await dc.continueDialog();
        } else {
            await dc.beginDialog(this.rootDialogId);
        }

        await next();
    }

    public async handleTeamsSigninVerifyState(context: TurnContext, state: SigninStateVerificationQuery): Promise<void> {
        await this.dialog.run(context, this.dialogState); // getting error here.
    }
}

`

Here w.r.t dialog and dialogState  create new attributes.
In **this.dialog** there is no **run()**. 

Could you please suggest.

Thanks,
Sreekanth

**Comment by Batta32** [comment]
Hi @SreekanthOAuth! If you are not able to use the run method, you should add a type for `T` which contains that method, as follows:
1. Update `DialogBot` class as `DialogBot<T extends MainDialog> extends TeamsActivityHandler` or directly specify a concrete type for dialog as `dialog: MainDialog`.
2. Implement the [run method](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/implement-teams-signin/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts#L408) in `MainDialog`.

You can check those changes in our [pushed branch](https://github.com/microsoft/botframework-solutions/tree/feature/southworks/implement-teams-signin) with a modified [Virtual Assistant Sample](https://github.com/microsoft/botframework-solutions/tree/feature/southworks/implement-teams-signin/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant) that implements the Teams Sign In.

Finally, you can take a look at the [NodeJS Sample 46](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/46.teams-auth) for how it implements the [run method with waterfall dialog](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/46.teams-auth/dialogs/mainDialog.js#L39).

Let us know if this helps or you have any other issue 😊.

**Comment by lauren-mills** [comment]
Closing due to inactivity. Please reopen as needed.

**Comment by YammanureSreekanth** [comment]
@lauren-mills , could you please reopen the issue as the issue still exists.

We have tried your suggestions based on recent comments. However, we are still encountering with the problem.

The real issue over here is,
- MS team channel doesn't support EndOfConversation activity type which is returned from the skill bot.

Please do let us know if you need any additional information.

Thanks,
Sreekanth From Ecolab.

**Comment by VictorGrycuk** [comment]
Hi @SreekanthOAuth!

We are looking into this.

**Comment by VictorGrycuk** [comment]
Hi @SreekanthOAuth,

We were able to reproduce your issue using the **master** branch, but also made the same test on **next** and it worked without issues.

These are the steps we followed to reproduce the issue:

1. Deploy a [Sample Virtual Assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant)
2. Deploy a [Sample Skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill)
3. Create a [Sample Skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill), but make sure to use different utterances, questions, and answers to differentiate it from the first skills, such as:
   - [SampleResponses.json](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/responses/sample/resources/SampleResponses.json)
   - [sampleSkill.lu](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/resources/LU/en-us/sampleSkill.lu)
4. After deploying the Virtual Assistant and the Skills, connect both Skills to the Virtual Assistant using the command `botskills connect --remoteManifest "http://localhost:<SKILL_PORT>/api/skill/manifest" --luisFolder "<PATH_TO_LUIS_FOLDER>" --ts`
5. Start the Virtual Assistant, and run ngrok using the same port used to run the Virtual Assistant
![image](https://user-images.githubusercontent.com/39467613/73489699-cbfa9900-4389-11ea-8f39-7f631f0813a1.png)
6. In Azure Portal, go to the Virtual Assistant bot resource, **Settings** > **Messaging Endpoint** and configure the ngrok URL
![image](https://user-images.githubusercontent.com/39467613/73489725-d61c9780-4389-11ea-8dc1-c231312a8d3c.png)
7. Create a `manifest.json` of the Virtual Assistant to use it on Teams [following these steps](https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-teams/4-create-app-manifest/)
   - Alternatively, use the manifest of the sample [Teams Conversation Bot](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/57.teams-conversation-bot/teamsAppManifest/manifest.json) as template, along with its icons
   - Make sure to replace `<<YOUR-MICROSOFT-APP-ID>>` with the appID of the Virtual Assistant
8. Zip the `manifest.json` and the icon files, and import it to Teams
![image](https://user-images.githubusercontent.com/39467613/73489757-ee8cb200-4389-11ea-9c33-b904775f5ad7.png)
9. Initialize the Virtual Assistant application and send the utterance of the first Sample Skill
10. After finishing with the waterfall dialog of the Sample Skill, an exception will be thrown:
![image](https://user-images.githubusercontent.com/39467613/73489789-fba9a100-4389-11ea-9513-2e45c7bde6c4.png)
11. The exception is thrown in the method `deserializeResponseBody()` of the file `deserializationPolicy` in `ms-rest-js`:
![image](https://user-images.githubusercontent.com/39467613/73489836-111ecb00-438a-11ea-9a23-88952d0e3cf9.png)

We also did the same test using the **next** branch, and the issue was not found
![image](https://user-images.githubusercontent.com/39467613/73489853-19770600-438a-11ea-935c-b1090729eb90.png)
As it can be seen in the image above, after finishing the waterfall dialog, the first Skill Sample hands off the control to the Virtual Assistant, then the utterance for the second Skill Sample is sent (`alternative`) and it is executed successfully, as noted by the "*What else can I help you with?*" sent by the Virtual Assistant.

**Note:** To use the `next` branch, it is necessary to build the [BotBuilder Solutions](https://github.com/microsoft/botframework-solutions/tree/next/sdk/typescript/libraries/botbuilder-solutions) and [BotBuilder Skills](https://github.com/microsoft/botframework-solutions/tree/next/sdk/typescript/libraries/botbuilder-skills) locally, and update the `package.json` of both the Virtual Assistant and Skill to use the local `.tgz` files, as they are not released yet.

This means that this issue will be fixed in the soon to be released version of TypeScript library.

**Comment by YammanureSreekanth** [comment]
Sorry for the late reply. I'll check and give an update.

**Comment by VictorGrycuk** [comment]
Hi @SreekanthOAuth,
The `next` branch has been merged with the `master` branch.

Please test again with the newly implemented changes.

**Comment by darrenj** [comment]
Please re-open if you run into the issue again

**Comment by amistry79** [comment]
Please re-open this. We tried to fixed based on the suggestion "replacing" ActivityType.EndOfConversation to ActivityType.HandOff and implementing TeamActivityHander. However, the fundamental issue is EndOfConversation ActivityType is not supported by MSTeam. We are really stuck and can not promise our internal stakeholders for MSTeam bot availability.
