### ISSUE TITLE
Virtual Assistant updated to 4.7.1 messaging endpoint exception

### ISSUE THREAD

**Issue by rvallireply** [microsoft/botframework-solutions#2888]
#### What project is affected?
Microsoft.Bot.Builder.Solution
#### What language is this in?
C#
#### What happens?

```
Error 500

TypeLoadException: Could not load type 'Microsoft.Bot.Builder.Solutions.IFallbackRequestProvider' from assembly 'Microsoft.Bot.Builder.Solutions, Version=4.6.0.0
```

#### What are the steps to reproduce this issue?

- In a Virtual Assistant project upgrade all nuget packages to latest version (4.7.1)
- debug Virtual Assistant project
- Navigate to http://localhost:3978/api/messages

#### What were you expecting to happen?

No error

#### Can you share any logs, error output, etc.?

```

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Microsoft.Bot.Builder.Solutions.IFallbackRequestProvider' from assembly 'Microsoft.Bot.Builder.Solutions, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetrySaveBodyASPMiddleware.Invoke(HttpContext httpContext) in d:\a\1\s\libraries\integration\Microsoft.Bot.Builder.Integration.ApplicationInsights.Core\TelemetrySaveBodyASPMiddleware.cs:line 58
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
System.TypeLoadException: Could not load type 'Microsoft.Bot.Builder.Solutions.IFallbackRequestProvider' from assembly 'Microsoft.Bot.Builder.Solutions, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

**Comment by lauren-mills** [comment]
Hi @rvallireply, we are in the process of updating our projects to support 4.7.1 but it is not complete yet. It is not recommended that you update your Bot Builder packages until our next release.

**Comment by darrenj** [comment]
Here are the steps - let us know how you get on
https://microsoft.github.io/botframework-solutions/overview/whats-new/0.8-beta/Summary/
