### ISSUE TITLE
Steps for creating and adding skills to VA

### ISSUE THREAD

**Issue by csnarain** [microsoft/botframework-solutions#2983]
Where can I find the correct steps to add skills to VA? I'm hosting both my VA and the skill in Azure. I followed the steps in the documentation (microsoft.github.io) to publish the skill but unable to 
make the skill work.

**Comment by darrenj** [comment]
Hosting both VA and Skill in Azure is a primary use case and the tutorial [here](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/7-add-your-skill/) is one we validated as part of the release we published yesterday so all should be OK?

Are you using the latest 0.8 template (published Monday) or something created previously?

**Comment by csnarain** [comment]
> 
> 
> Hosting both VA and Skill in Azure is a primary use case and the tutorial [here](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/7-add-your-skill/) is one we validated as part of the release we published yesterday so all should be OK?
> 
> Are you using the latest 0.8 template (published Monday) or something created previously?

Yes, I used the latest template for deployment. The problem is the VA is not able to forward the utterances to the skill. I'd also like to know if it's possible to add these skills to PVA? I tried using the new manifests but PVA keeps throwing errors.

**Comment by csnarain** [comment]
> 
> 
> > Hosting both VA and Skill in Azure is a primary use case and the tutorial [here](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/7-add-your-skill/) is one we validated as part of the release we published yesterday so all should be OK?
> > Are you using the latest 0.8 template (published Monday) or something created previously?
> 
> Yes, I used the latest template for deployment. The problem is the VA is not able to forward the utterances to the skill. I'd also like to know if it's possible to add these skills to PVA? I tried using the new manifests but PVA keeps throwing errors.

I digged a bit deeper and caught the error from my emulator (see below)

: "Exception Message: Failed to acquire token for client credentials. (Value cannot be null. (Parameter 'resource')) (Value cannot be null. (Parameter 'resource')) (Value cannot be null. (Parameter 'resource')) (Value cannot be null. (Parameter 'resource')) (Value cannot be null. (Parameter 'resource')) (Value cannot be null. (Parameter 'resource')) (Value cannot be null. (Parameter 'resource')) (Value cannot be null. (Parameter 'resource')) (Value cannot be null. (Parameter 'resource')) (Value cannot be null. (Parameter 'resource')) (Value cannot be null. (Parameter 'resource')), Stack: at Microsoft.Bot.Connector.Authentication.Retry.Run[TResult](Func`1 task, Func`3 retryExceptionHandler)
 at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.GetTokenAsync(Boolean forceRefresh)
 at Microsoft.Bot.Connector.Authentication.AppCredentials.GetTokenAsync(Boolean forceRefresh)
 at Microsoft.Bot.Builder.Solutions.Skills.SkillWebSocketTransport.ForwardToSkillAsync(SkillManifest skillManifest, IServiceClientCredentials serviceClientCredentials, ITurnContext turnContext, Activity activity, Action`1 tokenRequestHandler)
 at Microsoft.Bot.Builder.Solutions.Skills.SkillDialog.ForwardToSkillAsync(DialogContext innerDc, Activity activity)
 at Microsoft.Bot.Builder.Solutions.Skills.SkillDialog.ForwardToSkillAsync(DialogContext innerDc, Activity activity)
 at Microsoft.Bot.Builder.Solutions.Skills.SkillDialog.OnBeginDialogAsync(DialogContext innerDc, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.ComponentDialog.BeginDialogAsync(DialogContext outerDc, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
 at EYAssistant.Dialogs.MainDialog.OnMessageActivityAsync(DialogContext innerDc, CancellationToken cancellationToken) in C:\Users\lakshminarayanan.s\source\repos\EYAssistant\EYAssistant\Dialogs\MainDialog.cs:line 273
 at Microsoft.Bot.Builder.Solutions.Dialogs.ActivityHandlerDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken)
 at EYAssistant.Dialogs.MainDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken) in C:\Users\lakshminarayanan.s\source\repos\EYAssistant\EYAssistant\Dialogs\MainDialog.cs:line 96
 at Microsoft.Bot.Builder.Dialogs.ComponentDialog.BeginDialogAsync(DialogContext outerDc, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Teams.TeamsActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
 at EYAssistant.Bots.DefaultActivityHandler`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Users\lakshminarayanan.s\source\repos\EYAssistant\EYAssistant\Bots\DefaultActivityHandler.cs:line 39
 at Microsoft.Bot.Builder.Solutions.Feedback.FeedbackMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Solutions.Feedback.FeedbackMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)"

**Comment by darrenj** [comment]
Update - I've worked with @csnarain and he now has productivity skills working with both a BF VA and a Power Virtual Agent. There was some configuration steps to follow and appears there might be a `botskills` issue not adding everything to the local appSettings.json. Manually added and things are working end to end. Investigating a repro.

**Comment by darrenj** [comment]
Pushed a new version of botskills that has additional validation of a manifest and will catch an issue whereby the manifest hasn't been updated from the basic template provided therefore avoiding this condition moving forward.
