### ISSUE TITLE
Error adding skill to VA

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3190]
#### What project is affected?
ITSM and Calendar Skill
#### What language is this in?
c@

#### What happens?
Getting following error

smskill\Deployment\Resources\LU" --languages "en-us" --cs
Updating Dispatch
Adding skill to Dispatch
Parsing en-us ITSMSkillLuModel-en LU file
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: There was an error in the ludown parse command:
Command: ludown parse toluis --in "D:\itsmskill\Deployment\Resources\LU\en-us\ITSM.lu" --luis_culture en-us --out_folder "D:\itsmskill\Deployment\Resources\LU\en-us" --out itsm.luis
Error: The execution of the ludown command failed with the following error:
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'C:\Users\Gagan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

#### What are the steps to reproduce this issue?

Run following command

 botskills connect --remoteManifest "http://xx/manifest/manifest-1.1.json" --luisFolder "D:\Deployment\Resources\LU" --languages "en-us" --cs

**Comment by darrenj** [comment]
Thanks. Could you confirm that the `ludown` CLI tool is installed globally (e.g. npm install -g ludown) please and which OS you are using?

**Comment by gagankohli2000** [comment]
@darrenj I have ludown installed but its still giving same error. I believe some issue with my installation. Will try uninstalling and reinstalling again.

**Comment by Batta32** [comment]
Thanks @gagankohli2000! We will be reproducing the issue and we will back to you later 😊!

**Comment by DiegoCardozo94** [comment]
Hi @gagankohli2000

We found an [issue ](https://github.com/microsoft/botframework-solutions/issues/2336#issuecomment-530952165)that had a similar problem and could be a possible fix related this issue that appear when executes the connect command. Here is the [link ](https://github.com/microsoft/botframework-solutions/issues/2336#issuecomment-532546138)to the issue and the solution that the user implement to fix this.

Let us know if this solution resolves your problem 😊.

**Comment by Batta32** [comment]
Hi @gagankohli2000, we are closing this issue due to inactivity. Please, feel free to reopen it if you are still having the problem 😊.
