### ISSUE TITLE
Problem during the integration of bot with skill

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botframework-solutions#3278]
#### What project is affected?
VA 0.8
#### What language is this in?
C#
#### What are the steps to reproduce this issue?
https://microsoft.github.io/botframework-solutions
Created VA, skill, registered skill using 
 
  C:\msazure\EngSys\Obi\MicroServices\VirtualAssistant\VirtualAssistant>botskills connect --remoteManifest https://NewIcmSkills-tbvv5pz.azurewebsites.net/manifest/manifest-1.1.json --cs
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: Path to the LU file (C:\msazure\EngSys\Obi\MicroServices\VirtualAssistant\VirtualAssistant\Deployment\Resources\Skills\en-us\IcM.lu) leads to a nonexistent file.
Then did this
botskills connect --remoteManifest https://NewIcmSkills-tbvv5pz.azurewebsites.net/manifest/manifest-1.1.json --cs --luisFolder C:\msazure\EngSys\Obi\MicroServices\skills\IcM\IcM\Deployment\Resources\LU
	which worked (not sure whether this is the right step though)

Then I run the skill project, VA project and test the skill in bot emulator by invoking the sample dialog which produces this trace
text: "Exception Message: Error invoking the skill id: "IcM" at "https://newobi-ki6pa7f.azurewebsites.net/api/messages" (status is 500). 
 , Stack: at Microsoft.Bot.Solutions.Skills.SkillDialog.SendToSkillAsync(DialogContext dc, Activity activity, CancellationToken cancellationToken)
 at Microsoft.Bot.Solutions.Skills.SkillDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
 at VirtualAssistant.Dialogs.MainDialog.RouteStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken) in C:\msazure\EngSys\Obi\assistant\src\VirtualAssistant\Dialogs\MainDialog.cs:line 329
 at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.OnStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.RunStepAsync(DialogContext dc, Int32 index, DialogReason reason, Object result, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.Prompt`1.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
 at VirtualAssistant.Dialogs.MainDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken) in C:\msazure\EngSys\Obi\assistant\src\VirtualAssistant\Dialogs\MainDialog.cs:line 160
 at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Teams.TeamsActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
 at VirtualAssistant.Bots.DefaultActivityHandler`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\msazure\EngSys\Obi\assistant\src\VirtualAssistant\Bots\DefaultActivityHandler.cs:line 41
 at Microsoft.Bot.Solutions.Feedback.FeedbackMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)"

#### What were you expecting to happen?
Sample dialog invokes ICM skill
#### Can you share any logs, error output, etc.?
Above

**Comment by ipraveenMS** [comment]
I found out the issue.
