### ISSUE TITLE
SSO doesn't work between virtual assistant and calendar skill

### ISSUE THREAD

**Issue by dingjianrui** [microsoft/botframework-solutions#3571]
#### What project is affected?

1. Virtual Assistant
2. Calendar Skill

#### What language is this in?
English
#### What happens?
Calendar Skill get graph token failed
#### What are the steps to reproduce this issue?
1. Create the virtual assistant by the template.
2. Clone the Calendar skill and deployed.
#### What were you expecting to happen?
The Calendar Skill should be able to get the graph token by a exchangeable token from VA.
#### Can you share any logs, error output, etc.?
**I have two Azure subscriptions:**
Subscription A:
I deployed all the VA and Skills resources/services in the subscription. and i also created two app registrations for creating the Bot Services, these two app are required while you create the Bot Channel registration.
Subscription B:
I created two app registrations(app identity), one for VA and another for Calendar Skill, these two app are especially used for accessing the Graph API and read the mail from O365, so i use them to configure the **OAuth Connection Settings** in the Azure Bot Services. (I followed the SSO sample to create these two app, Link: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml#create-the-azure-ad-identity-for-rootbot)
But one thing really confused me a lot, there is a config in the Calendar Skill which is called "oauthCredentials", i have no idea what it is used for. 
`"oauthConnections": [
    {
      "name": "CalendarConn",
      "provider": "Azure Active Directory v2"
    }
  ],
  "oauthCredentials": {
    "microsoftAppId": "dxxxx",
    "microsoftAppPassword": "xxxxx"
  },`
#### Any screenshots or additional context?
if i Configure the oauthCredentials with the app id and secret from subscription A i mentioned above, i can find that the VA can get the exchangeable token successfully and forward it to the Calendar Skill, but the calendar skill cannot get a graph token by this exchangeable token.
If i configure the oauthCredentials with the app id and secret from subsciption B i mentioned above, The VA will not get any exchange token request from Calendar Skill and The Calendar Skill get an error like this "Operation returned an invalid status code 'Unauthorized'", and the stack information are below:
`  at Microsoft.Bot.Connector.UserToken.<GetTokenWithHttpMessagesAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.UserTokenExtensions.<GetTokenAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.BotFrameworkAdapter.<GetUserTokenAsync>d__42.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.OAuthPrompt.<BeginDialogAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<BeginDialogAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<PromptAsync>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Solutions.Authentication.MultiProviderAuthDialog.<PromptForAuthAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<OnStepAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<RunStepAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<ResumeDialogAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.WaterfallStepContext.<NextAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Solutions.Authentication.MultiProviderAuthDialog.<PromptForProviderAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<OnStepAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<RunStepAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<BeginDialogAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<BeginDialogAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Solutions.Authentication.MultiProviderAuthDialog.<FirstStepAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<OnStepAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<RunStepAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<BeginDialogAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<BeginDialogAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.<BeginDialogAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<BeginDialogAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<PromptAsync>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CalendarSkill.Dialogs.CalendarSkillDialogBase.<GetAuthTokenAsync>d__19.MoveNext() in D:\Source\Bot\botframework-skills\skills\csharp\calendarskill\Dialogs\CalendarSkillDialogBase.cs:line 123`

Thanks.

**Comment by lauren-mills** [comment]
Hi @dingjianrui, hopefully I can clarify this scenario.

The oAuthCredentials property allows the Calendar Skill to use the same authentication credentials as the VA, so that you do not have to log in multiple times for multiple skills. If you provide the oAuthCredentials property in the Calendar Skill, that Microsoft App registration needs to have the desired scopes for the Microsoft Graph resources you need to access. So your VA bot registration would need to be configured to access the Calendars.ReadWrite scope, etc. (matching the calendar skill documentation).

If you do not provide the oAuthCredentials property in the skill, it will use the Calendar Skill app registration for logging in and the calendar scopes need to be provided on that bot registration. 

Please let me know if this helps.

**Comment by dingjianrui** [comment]
@lauren-mills Thanks for your feedback. i tried it based on your suggestion, but it still not working. i have some other information to share with you.

**For the VA, i have two app registrations, and they are in different ADD tenant:**
APP Registration A - this one is used while i creating the Bot Service Channel, used as bot appid and secret.
APP Registration B -  this one is used for creating the OAuth connections in the Bot service Channel, used for getting the graph token for graph API access.

if i use the "APP Registration A(Appid&secret)" as the oauth credentials in the calendar skill, the error is "**Operation returned an invalid status code 'BadRequest'**".
if i use the "APP Registration B(Appid&secret)" as the oauth credentials in the calendar skill, the error is "**Operation returned an invalid status code 'Unauthorized'**".

But the tricky thing is that, based on the SSO authentication diagram below, if the skill cannot find the cached token from the token service, usually it will send the OAuthCard to the VA first, and ask the user to login, but no matter which appid/secret i used above, the calendar skill didn't send the OAuthCard to the VA.

<img width="350" alt="auth-bot-sso-sample-flow-diagram" src="https://user-images.githubusercontent.com/1256355/88023837-54e9d480-cb64-11ea-88d7-9df49482ee37.png">

Is there a way that i can clean up the cached token from the bot token service, and force the bot to re-login?
many thanks.

**Comment by lauren-mills** [comment]
I'm a little confused about your app registrations. Can you confirm if they are set up like this?

App Registration 1 (VA): Used to register VA bot (no MS Graph permissions applied)
App Registration 2 (Calendar): Used to register Calendar skill (MS Graph scopes applied)

Also, you should be able to use this method for for clearing out your cached tokens: https://github.com/microsoft/botframework-solutions/blob/471ea107e045bdf5a401b4ddd4a3d8720dcd78ad/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs#L435

**Comment by lauren-mills** [comment]
I just verified that I was able to deploy a new VA and the Calendar Skill. First I configured the MS Graph oauth scopes on the calendar skill itself, and set the oauthCredentials property in appsettings.json to use the Calendar Skill MS app Id and password. This seems to work fine, and allows the user to log in. 

Then, I switched to the SSO model, by applying the MS Graph scopes to the VA MS app registration, and changing the oauthCredentials property to use the VA MS app Id and password. This also worked as expected.

Please let me know if there is a different requirement in your implementation.

**Comment by dingjianrui** [comment]
> I just verified that I was able to deploy a new VA and the Calendar Skill. First I configured the MS Graph oauth scopes on the calendar skill itself, and set the oauthCredentials property in appsettings.json to use the Calendar Skill MS app Id and password. This seems to work fine, and allows the user to log in.
> 
> Then, I switched to the SSO model, by applying the MS Graph scopes to the VA MS app registration, and changing the oauthCredentials property to use the VA MS app Id and password. This also worked as expected.
> 
> Please let me know if there is a different requirement in your implementation.


@lauren-mills The situation here is a little bit different, please refer to the diagram below:
VA Settings:
![Image 1](https://user-images.githubusercontent.com/1256355/88115777-8953a400-cbe9-11ea-9bb7-b86ac5c97c3a.png)
**********************************************************************
Calendar Skill Settings:
(Note: VA's O365 connection and Calendar Skill's M365Connection use the same appid/secret)
![Image 5](https://user-images.githubusercontent.com/1256355/88116497-41ce1780-cbeb-11ea-8f6e-415ad3890256.png)

The reason why i used two AAD tenants is because i have Azure subscription in tenant A, i can setup the VA and skills environment in here, but i cannot grant API permission to the app registration, because it needs consent from admin. so i'm not able to test the graph API with app registration in tenant A.
In the AAD tenant B, i can consent on the API permission, so i'm able to read calendar via the graph API. But i have no subscription associated with the tenant B, so i cannot setup my VA and skills environment here.
with this configurations, the Calendar can work without VA engaged, but SSO cannot work between them.

Thanks.

**Comment by lauren-mills** [comment]
Ah, okay I see now. I'm looking into it more. Thanks!

**Comment by lzc850612** [comment]
@dingjianrui for App Registration B, is it a multi-tenant app? that reflects on the SignInAudience property of the manifest of the ms app, and its value should be 	

"signInAudience": "AzureADandPersonalMicrosoftAccount",

I'm suspecting your problem should be related to this setting as when you're using the credentials of app registration B you're getting an unauthorized error, despite it being correct.

Thanks.

**Comment by dingjianrui** [comment]
> AzureADandPersonalMicrosoftAccount

@lzc850612 ,you are right, it's multi-tenant app, and the "SignInAudience" property of manifest of the app is "AzureADandPersonalMicrosoftAccount"
