### ISSUE TITLE
Trouble Opening Analytics Template

### ISSUE THREAD

**Issue by mmarzillo** [microsoft/botframework-solutions#3704]
When I go to open the template I get the below error.
![image](https://user-images.githubusercontent.com/6752474/98865146-9a425280-2430-11eb-848c-44d5ba5ca519.png)

**Comment by Batta32** [comment]
Hi @mmarzillo , thanks for reporting this issue. We came up with some **questions** to complete the description of this issue so we can reproduce it:
1. With _Analytics Templates_, are you referring to [/solution-accelerators/tutorials/view-analytics/3-open-template/](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/3-open-template/) document?
1. Can you add the _Repro Steps_ that you are following and your _Environment_?
1. Which should be the behavior that you are expecting?
1. Is there something relevant you want to mention here?

We will be attentive to your reply so we can start working to reproduce this issue 😊.

**Comment by mmarzillo** [comment]
1. Yes
2. I'm clicking "Virtual Assistant analytics template" downloading the template then opening it. I'm on Windows 10 with Power Bi version 2.87
3. I'm expecting to presented with a screen asking for the application insights id. 
4. I think that's it, could be something simple as this is my first time working through the tutorial.

**Comment by Batta32** [comment]
Thanks @mmarzillo for your quick reply, we will start reviewing this issue with the answers you added. As soon as we have any status, we will let you know here 😊!

**Comment by Batta32** [comment]
Hi @mmarzillo, currently we are working on this issue, trying to reproduce the problem. This week we will have an update that we will communicate it here 😊.

**Comment by matiasroldan6** [comment]
Hi @mmarzillo, we couldn't reproduce this error, could you please attach the output from clicking **Copy details** in your error notification? That should print a more detailed log that could be useful to us.

We followed the [/solution-accelerators/tutorials/view-analytics/3-open-template/](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/3-open-template/) document having Power BI version 2.87.

We found some alternatives that you can try to fix the error:

- **Reset Power BI**
    1. Go to Settings > Apps > Apps & features menu in Windows
    1. Select Power BI from the list of programs
    1. Click Reset
- **Reinstall Power BI**

Keep in mind that if you have data or configurations that you don't wish to lose maybe you wouldn't want to try those alternatives.

We believe this issue could be related to the Power BI installation. The _Class not registered_ error is a common Windows 10 error that can happen when a required dll becomes unregistered.

Just in case, we also confirmed that this doesn't seem to be a problem with the template being corrupted.

We will be attentive to your response.

_Reset button related to the first alternative_
![image](https://user-images.githubusercontent.com/20074735/99445802-d546f900-28fc-11eb-90f2-bb7fc810ee97.png)

**Comment by mmarzillo** [comment]
I tried Resetting PowerBi and the uninstalling and re-installing, but it's still doing the same thing with that same download you're showing.

Here are the results from "Copy Details."

_Feedback Type:
Frown (Error)

Error Message:
Failed to save modifications to the server. Error returned: 'The following system error occurred:  Class not registered 
'.

Stack Trace:
   at Microsoft.PowerBI.Client.Windows.Storage.FileOpenError.HandleError(IWindowService windowService, LocalizedString title)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.TryImportTemplate(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, TelemetryUserActionId entryPoint, Boolean& editQueries, String filePath)
   at Microsoft.PowerBI.Client.Windows.Commands.ApplicationCommands.DataImportCommands.ImportTemplate(IPowerBIWindowService windowService, IExceptionHandler exceptionHandler, ImportTemplateParameters parameters)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)

Stack Trace Message:
Failed to save modifications to the server. Error returned: 'The following system error occurred:  Class not registered 
'.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass15_0.<HandleException>b__0()
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.PowerBI.Client.Windows.Utilities.UIBlockingAwareExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<>c__DisplayClass4_0.<.ctor>b__0(Object arg)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<Execute>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.Execute(Object parameter)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.<Execute>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(ICommand command, Object parameter)
   at Microsoft.Practices.Prism.Commands.CompositeCommand.Execute(Object parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_7.<<Main>b__8>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_7.<Main>b__8(MainWindow mainWindow)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<<ActivateMainWindow>b__114_1>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<ActivateMainWindow>b__114_1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAwaitableAsyncExceptions>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAwaitableAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAsyncExceptions>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<ActivateMainWindow>b__114_0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_0.<Main>b__1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)


PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.87.684.0","ModuleName":"Microsoft.PowerBI.Client.Windows.dll","Component":"Microsoft.PowerBI.Client.Windows.Storage.FileOpenError","Error":"Microsoft.AnalysisServices.OperationException","MethodDef":"HandleError - PFE_SYSTEM","ErrorOffset":"110"}

Snapshot Trace Logs:
C:\Users\mmarzillo\Microsoft\Power BI Desktop Store App\FrownSnapShotf5c7e9d9-ce3c-4552-b720-70cc1e62ad8f.zip

Model Default Mode:
Empty

Model Version:
PowerBI_V1

Is Report V3 Models Enabled:
True

Performance Trace Logs:
C:\Users\mmarzillo\Microsoft\Power BI Desktop Store App\PerformanceTraces.zip

Enabled Preview Features:
PBI_NewWebTableInference
PBI_v3ModelsPreview

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_JsonTableInference
PBI_ImportTextByExample
PBI_ExcelTableInference
PBI_qnaLiveConnect
PBI_azureMapVisual
PBI_dataPointLassoSelect
PBI_narrativeTextBox
PBI_dynamicParameters
PBI_anomalyDetection
PBI_newFieldList

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
MSIT

PowerBINonFatalError_MethodDefDescription:
PFE_SYSTEM

PowerBIUserFeedbackServices_IsReported:
True

Formulas:


section Section1;_

**Comment by Batta32** [comment]
Thanks @mmarzillo for sharing this information. We will review it and try to find the best approach for you 😊.

**Comment by mmarzillo** [comment]
So I wound up uninstalling PowerBI and re-installing an older version (2.85.985.0) and it worked. I'm going to close this, thanks for your help in digging into this!

**Comment by Batta32** [comment]
Awesome @mmarzillo! If you have any other problem, feel free to open a new issue in the repository 😊.
