### ISSUE TITLE
Operation returned an invalid status code 'NotFound' when calling TeamsOperations.FetchChannelListWithHttpMessagesAsync

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botframework-solutions#3757]
#### What project is affected?
latest BF 
#### What language is this in?
C#
#### What happens?
Operation returned an invalid status code 'NotFound'
   at Microsoft.Bot.Connector.Teams.TeamsOperations.GetResponseAsync[T](String url, Boolean shouldTrace, String invocationId, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.Teams.TeamsOperations.FetchChannelListWithHttpMessagesAsync(String teamId, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.Teams.TeamsOperationsExtensions.FetchChannelListAsync(ITeamsOperations operations, String teamId, CancellationToken cancellationToken)
   at GetChannelList(CancellationToken cancellationToken) in C:\...\TeamsContext\TeamsContext.ChannelExtensions.cs:line 46

#### What are the steps to reproduce this issue?
Called the above function to retrieve some teams info and hit this error.
#### What were you expecting to happen?
Success.
#### Can you share any logs, error output, etc.?
Above.
Also 
This is the post from previous UpdateActivity that was successful (from ngrok)
POST /api/skills/v3/conversations/19:74344caa321c411591735f7122d017ac@thread.tacv2;messageid=1611212147390-l_Icm-msteams-skillconvo/activities/1611212147390   
200 OK
This corresponds to the failure (above)
GET /api/skills/v3/teams/19:74344caa321c411591735f7122d017ac@thread.tacv2/conversations    
404 Not Found

**Comment by Batta32** [comment]
Hi @ipraveenMS, thanks for reporting the issue.

We came up with some **questions** in order to reproduce the issue:
1. Can you add a detailed repro steps so we can follow exactly the same steps?
1. Can you add the environment that you have configured? For example, if you are using a VA-Skill connection, if you are using Teams as channel
1. Which version of `botbuilder` are you using?

We will let you know as soon as we have any update 😊.

**Comment by ipraveenMS** [comment]
@Batta32 
1. I am using VA and skills. Called UpdatedActivityAsync from skill which works (POST http message above) and I call TeamsConnectorClient.Teams.FetchChannelListAsync from skill which fails (GET http message above returns NOT found). 
2. Its a regular VA and skills project (modified with our changes) and teams is configured as a channel in both skill and VA and messages are posted to teams just fine except this error.
3. BF version is 4.11.1

**Comment by ipraveenMS** [comment]
So I noticed one thing, the UpdateActivityAsync calls from skill hit a corresponding function in the VA side (SkillController:UpdateActivityAsync)  REST path: v3/**conversations**/activities HTTP POST
But when TeamsConnectorClient.Teams.FetchChannelListAsync function is called from skill, no function gets hits on VA side . There is no matching path that handles the v3/**teams**/conversations HTTP GET

So I this this is why VA return "not found" error because it cannot find a path that handles that REST API that got called. Not because it cannot find the data. It would be great it you look into this.

**Comment by ipraveenMS** [comment]
Even 
  var details = await TeamsInfo.GetTeamDetailsAsync(turnContext,
                turnContext.Activity.TeamsGetTeamInfo().Id, cancellationToken);
hit the same NOT found error. With same REST path in ngrok

**Comment by ipraveenMS** [comment]
Hi @Batta32 any updates?

**Comment by Batta32** [comment]
Hi @ipraveenMS , sorry for the delay. We are going to tackle this issue during this week, as soon as we have any update, we will let you know here 😊.

**Comment by Virtual-Josh** [comment]
@Batta32 have you had a chance to dig into this? If so, can you provide an update?

**Comment by VictorGrycuk** [comment]
Hi @ipraveenMS @Virtual-Josh, we were able to reproduce the issue you mention by calling `TeamsInfo.GetTeamDetailsAsync()` method, however, this seems to be a behaviour caused by [BotBuilder SDK](https://github.com/microsoft/botbuilder-dotnet/).

The reason seems to be that since it's the Assistant the one actually communicating on the Teams channel, and the Skill communication only happens through the Assistant, leads to the malformation of a URL. Below you can find the explanation on how we reached this conclusion.

We will continue trying to find a solution for this issue, but please feel free to open an issue in [BotBuilder-DotNet](https://github.com/microsoft/botbuilder-dotnet/).

### Research
This was our environment:

- Master's Sample [Virtual Assistant](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant)
- Master's Sample [Skill](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/skill/SkillSample) connected to the Sample Virtual Assistant
- Both with Teams channel enabled

We did 3 different tests:

- Run the sample assistant on MS Teams and call `GetTeamDetailsAsync` from the sample assistant's DefaultActivityHandler. This had no issues, it returned the requested information (AadGroupId, Teams Id, etc.).
- Run the sample skill alone, not connected to the assistant, on MS Teams and call `GetTeamDetailsAsync` from the sample skill's DefaultActivityHandler. The same result as above, it returned the same information as it did with the sample assistant.
- Run the sample assistant on MS Teams with the sample skill connected, and call `GetTeamDetailsAsync` from the sample skills DefaultActivityHandler. This caused the same exception you described, status code `NotFound`.

We took a closer look at why the `/api/skills/v3/teams/{ID}/conversations` URL was causing this problem, and we found it is generated at the [TeamsOperations](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs#L97) class using `Client.BaseUri.AbsoluteUri` as prefix, with `Client` being a [ConnectorClient](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/ConnectorClient.cs).

To validate what base URI was being used, we modified our samples to retrieve said URI:

```
var baseUri = turnContext.TurnState.Get<IConnectorClient>().BaseUri;
```

In both scenarios where the `GetTeamDetailsAsync` works (calling it from the sample assistant, and calling it from the sample skill alone), the base URI was `https://smba.trafficmanager.net/amer/`, in the scenario where it fails (calling it from the sample skill when it is connected to the sample assistant) the URI was `http://localhost:3978/api/skills`. This was the in which our sample assistant was running locally.

So far we haven't found a way successfully to call `GetTeamDetailsAsync` from a skill connected to an assistant by modifying either the assistant or the skill.
