### ISSUE TITLE
TranscriptLoggerMiddleware logActivity failed: "Converting circular structure to JSON"

### ISSUE THREAD

**Issue by YammanureSreekanth** [microsoft/botframework-solutions#3763]
What project is affected?

sample-assistant and sample-skill

#### What language is this in?

Typescript

We are using the below versions

"botbuilder": "^4.11.0",
"botbuilder-ai": "^4.11.0",
Typescript
Node Js: v11.6.0
Windows 10

#### What happens?

Getting below error on Every time dialog is end

TranscriptLoggerMiddleware logActivity failed: "Converting circular structure to JSON"
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at AzureBlobTranscriptStore.<anonymous> (D:\Workspace\Ecolab\EVA-IT-TEST\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:65:31)

#### What were you expecting to happen?

This error shouldn't come.

#### Can you share any logs, error output, etc.?

TranscriptLoggerMiddleware logActivity failed: "Converting circular structure to JSON"
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at AzureBlobTranscriptStore.<anonymous> (D:\Workspace\Ecolab\EVA-IT-TEST\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:65:31)
    at Generator.next (<anonymous>)
    at D:\Workspace\Ecolab\EVA-IT-TEST\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Workspace\Ecolab\EVA-IT-TEST\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:10:12)
    at AzureBlobTranscriptStore.logActivity (D:\Workspace\Ecolab\EVA-IT-TEST\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:60:16)
    at TranscriptLoggerMiddleware.<anonymous> (D:\Workspace\Ecolab\EVA-IT-TEST\EVA-IT-SKILL\node_modules\botbuilder-core\lib\transcriptLogger.js:104:54)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Workspace\Ecolab\EVA-IT-TEST\EVA-IT-SKILL\node_modules\botbuilder-core\lib\transcriptLogger.js:11:58)

Thanks,
Sreekanth (Ecolab)

**Comment by mdrichardson** [comment]
@SreekanthOAuth 

1. Are you able to provide a longer stack trace? You should be able to adjust this by modifying your `package.json` > `start` line to include `node --stack-trace-limit=100`. 

2. Are you sending any data back as the result with the dialog ends? 

3. Is it every dialog, or just one in particular?

**Comment by YammanureSreekanth** [comment]
@mdrichardson , 

I have added node --stack-trace-limit=100 in my package.json like below,

 "start:dev": "npm run build && node --stack-trace-limit=100 ./lib/index.js NODE_ENV=development",

Below is the log coming on every time bot responds

TranscriptLoggerMiddleware logActivity failed: "Converting circular structure to JSON"
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at AzureBlobTranscriptStore.<anonymous> (D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:65:31)
    at Generator.next (<anonymous>)
    at D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:10:12)
    at AzureBlobTranscriptStore.logActivity (D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:60:16)
    at TranscriptLoggerMiddleware.<anonymous> (D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-core\lib\transcriptLogger.js:104:54)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-core\lib\transcriptLogger.js:11:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
TranscriptLoggerMiddleware logActivity failed: "Converting circular structure to JSON"
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at AzureBlobTranscriptStore.<anonymous> (D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:65:31)
    at Generator.next (<anonymous>)
    at D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:10:12)
    at AzureBlobTranscriptStore.logActivity (D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:60:16)
    at TranscriptLoggerMiddleware.<anonymous> (D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-core\lib\transcriptLogger.js:104:54)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Workspace\Ecolab\EVA-IT\EVA-IT-SKILL\node_modules\botbuilder-core\lib\transcriptLogger.js:11:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

It's coming for all the dialogs.

Please let me know if you need any further details.

Thanks,
Sreekanth

**Comment by mdrichardson** [comment]
@SreekanthOAuth The line that's failing has been in the code for 3 years, so I'm not sure exactly what's going on. Are you doing any manual editing of the `activity` object in your dialogs? 

We need to find out where the circular reference is occurring in your activity. Please add something like this to your `index.js`:

```js
// These should already exist for you, although likely with different names
// and maybe not ConsoleTranscriptLogger. That's okay/
const logstore = new ConsoleTranscriptLogger();
const middleware = new TranscriptLoggerMiddleware(logstore);

// We're going to use this to inspect circular references.
const { inspect } = require('util');

// Overwrite the logActivity method so we can figure out which activity is causing issues.
const originalLogActivity = middleware.logActivity;
middleware.logActivity = (transcript, activity) => {
    try {
        originalLogActivity(transcript, activity);
    } catch (err) {
        console.log(inspect(err));
        console.log(inspect(activity));
    }
};

adapter.use(middleware);
```

and then copy/paste the error and activity.

**Comment by congysu** [comment]
@mdrichardson could you please follow up with customer on this item?  Thanks.

**Comment by mdrichardson** [comment]
@SreekanthOAuth Were you able to log any errors?

**Comment by mdrichardson** [comment]
Closing due to inactivity. Feel free to re-open if you still have an issue.

**Comment by YammanureSreekanth** [comment]
@mdrichardson - Sorry for the late response. was into other priority issues.

While trying the above suggestion getting below message,

Property 'logActivity' is private and only accessible within class 'TranscriptLoggerMiddleware'.ts(2341)

Screenshot for the same

![image](https://user-images.githubusercontent.com/24246902/110344545-98417680-8053-11eb-9b71-18a2f1c6c696.png)


Please re-open this ticket.

Thanks,
Sreekanth

**Comment by mdrichardson** [comment]
@SreekanthOAuth For testing purposes, just place `// @ts-ignore` above that line.

**Comment by YammanureSreekanth** [comment]
@mdrichardson - I have tried with your suggestion, added below snippet in defaultAdapter.ts file

```
const transcriptStore: TranscriptStore = new AzureBlobTranscriptStore({
            containerName: EvaConfig.blobStorageContainerTranscript,
            storageAccountOrConnectionString: settings.blobStorage.connectionString
        });
        const middleware = new TranscriptLoggerMiddleware(transcriptStore);
        // @ts-ignore
        const originalLogActivity = middleware.logActivity;
        // @ts-ignore
        middleware.logActivity = (transcript, activity) => {
            try {
                originalLogActivity(transcript, activity);
            } catch (err) {
                console.log(inspect(err));
                console.log(inspect(activity));
            }
        };
        this.use(middleware);
```

But, this logic also not giving the detailed logs, it's giving the same old logs

```
TranscriptLoggerMiddleware logActivity failed: "Converting circular structure to JSON"
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at AzureBlobTranscriptStore.<anonymous> (D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:67:31)
    at Generator.next (<anonymous>)
    at D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:11:12)
    at AzureBlobTranscriptStore.logActivity (D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:62:16)
    at TranscriptLoggerMiddleware.<anonymous> (D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-core\lib\transcriptLogger.js:106:54)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-core\lib\transcriptLogger.js:12:58
```

Do you want to add this to index.ts?

Thanks,
Sreekanth

**Comment by YammanureSreekanth** [comment]
@mdrichardson - I have added the same logic in index.ts and still getting the same logs as mentioned above.

 ```
const transcriptStore: TranscriptStore = new AzureBlobTranscriptStore({
        containerName: EvaConfig.blobStorageContainerTranscript,
        storageAccountOrConnectionString: botSettings.blobStorage.connectionString
    });
    const middleware = new TranscriptLoggerMiddleware(transcriptStore);
    // @ts-ignore
    const originalLogActivity = middleware.logActivity;
    // @ts-ignore
    middleware.logActivity = (transcript, activity) => {
        try {
            originalLogActivity(transcript, activity);
        } catch (err) {
            console.log(inspect(err));
            console.log(inspect(activity));
        }
    };
    adapter.use(middleware);
```

Thanks,
Sreekanth

**Comment by mdrichardson** [comment]
@SreekanthOAuth The first part of the error should be the same, but it should also be logging the activity. If it's not, maybe try changing it to:

```js
middleware.logActivity = (transcript, activity) => {
       try {
       	   console.log(inspect(activity));
           originalLogActivity(transcript, activity);
       } catch (err) {
           console.log(inspect(err));
           console.log(inspect(activity));
       }
   };
```

Are you doing any manual editing of the `activity` object in your dialogs?

**Comment by YammanureSreekanth** [comment]
@mdrichardson - Please find the logs below

Before error message

```
{ type: 'event',
  name: 'ContinueConversation',
  channelId: 'directline',
  locale: 'en-US',
  serviceUrl: 'https://directline.botframework.com/',
  conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
  from:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a478',
     name: '',
     role: 'user' },
  recipient: { id: 'XXXXX-BOT-D@vLojGrm-9k4', name: 'EVA-DEV' },
  id: '9vpfF58NZbjDxNr6KxGp4G-f|0000002' }
{ type: 'typing',
  serviceUrl: 'https://directline.botframework.com/',
  channelId: 'directline',
  from: { id: 'XXXXXX-BOT-D@vLojGrm-9k4', name: 'EVA-DEV' },
  conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
  recipient:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a462',
     name: '',
     role: 'user' },
  locale: 'en-US',
  replyToId: '9vpfF58NZbjDxNr6KxGp4G-f|0000002',
  relatesTo:
   { activityId: '9vpfF58NZbjDxNr6KxGp4G-f|0000002',
     bot: null,
     conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
     channelId: 'directline',
     serviceUrl: 'https://directline.botframework.com/' },
  id: '9vpfF58NZbjDxNr6KxGp4G-f|Jc8Mi5JPiwj' }
{ type: 'event',
  name: 'ContinueConversation',
  channelId: 'directline',
  locale: 'en-US',
  serviceUrl: 'https://directline.botframework.com/',
  conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
  from:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a462',
     name: '',
     role: 'user' },
  recipient: { id: 'XXXXX-BOT-D@vLojGrm-9k4', name: 'XXX-DEV' },
  id: '9vpfF58NZbjDxNr6KxGp4G-f|0000002' }
{ type: 'typing',
  serviceUrl: 'https://directline.botframework.com/',
  channelId: 'directline',
  from: { id: 'XXXX-BOT-D@vLojGrm-9k4', name: 'XXX-DEV' },
  conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
  recipient:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a462',
     name: '',
     role: 'user' },
  locale: 'en-US',
  replyToId: '9vpfF58NZbjDxNr6KxGp4G-f|0000002',
  relatesTo:
   { activityId: '9vpfF58NZbjDxNr6KxGp4G-f|0000002',
     bot: null,
     conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
     channelId: 'directline',
     serviceUrl: 'https://directline.botframework.com/' },
  id: '9vpfF58NZbjDxNr6KxGp4G-f|7twAETq0Agu' }
{ type: 'event',
  name: 'ContinueConversation',
  channelId: 'directline',
  locale: 'en-US',
  serviceUrl: 'https://directline.botframework.com/',
  conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
  from:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a462',
     name: '',
     role: 'user' },
  recipient: { id: 'XXXXX-BOT-D@vLojGrm-9k4', name: 'XXX-DEV' },
  id: '9vpfF58NZbjDxNr6KxGp4G-f|0000002' }
{ type: 'message',
  serviceUrl: 'https://directline.botframework.com/',
  channelId: 'directline',
  from: { id: 'XXXXX-BOT-D@vLojGrm-9k4', name: 'XXX-DEV' },
  conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
  recipient:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a462',
     name: '',
     role: 'user' },
  attachmentLayout: 'list',
  locale: 'en-US',
  speak:
   'Please provide a detailed description of your request.',
  inputHint: 'acceptingInput',
  suggestedActions: { to: [], actions: [ [Object] ] },
  attachments:
   [ { contentType: 'application/vnd.microsoft.card.hero',
       content: [Object] } ],
  replyToId: '9vpfF58NZbjDxNr6KxGp4G-f|0000002',
  id: '9vpfF58NZbjDxNr6KxGp4G-f|0000003' }
```

Error message

```
TranscriptLoggerMiddleware logActivity failed: "Converting circular structure to JSON"
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at AzureBlobTranscriptStore.<anonymous> (D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:67:31)
    at Generator.next (<anonymous>)
    at D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:11:12)
    at AzureBlobTranscriptStore.logActivity (D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-azure\lib\azureBlobTranscriptStore.js:62:16)
    at TranscriptLoggerMiddleware.<anonymous> (D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-core\lib\transcriptLogger.js:106:54)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Workspace\Ecolab\EVA-IT\IT_EVA\node_modules\botbuilder-core\lib\transcriptLogger.js:12:58)
```

After error message

```
{ type: 'event',
  name: 'ContinueConversation',
  channelId: 'directline',
  locale: 'en-US',
  serviceUrl: 'https://directline.botframework.com/',
  conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
  from:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a462',
     name: '',
     role: 'user' },
  recipient: { id: 'XXXX-BOT-D@vLojGrm-9k4', name: 'XXX-DEV' },
  id: '9vpfF58NZbjDxNr6KxGp4G-f|0000002' }
{ type: 'typing',
  serviceUrl: 'https://directline.botframework.com/',
  channelId: 'directline',
  from: { id: 'XXXXX-BOT-D@vLojGrm-9k4', name: 'XXX-DEV' },
  conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
  recipient:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a462',
     name: '',
     role: 'user' },
  locale: 'en-US',
  replyToId: '9vpfF58NZbjDxNr6KxGp4G-f|0000002',
  relatesTo:
   { activityId: '9vpfF58NZbjDxNr6KxGp4G-f|0000002',
     bot: null,
     conversation: { id: '9vpfF58NZbjDxNr6KxGp4G-f' },
     channelId: 'directline',
     serviceUrl: 'https://directline.botframework.com/' },
  id: '9vpfF58NZbjDxNr6KxGp4G-f|Aop0eNJlr9A' }
```
Could you please give us some examples of which attributes should not be updated?

Thanks,
Sreekanth

**Comment by mdrichardson** [comment]
I can't tell for sure, but it looks like the issue might be in the activity with the message, "Please provide a detailed description of your request.". Can you please provide how you construct that message, including the suggested actions and the attachments?

I wouldn't say any attributes are completely off-limits, but it's pretty rare that you need to edit them directly. My concern, due to the error message, is that you're placing a circular reference in one of the activities.

**Comment by YammanureSreekanth** [comment]
@mdrichardson - 

I have tried removing the suggestion actions and still, the same error is coming

Giving one of our test dialogs which are asking feedback

```
this.askForFeedBack.bind(this),
this.captureFeedBack.bind(this),
this.captureFeedbackReason.bind(this)
```

askForFeedBack

![image](https://user-images.githubusercontent.com/24246902/110421076-c4481080-80c2-11eb-81c0-87d451d9c4c7.png)

captureFeedBack

![image](https://user-images.githubusercontent.com/24246902/110421101-d2962c80-80c2-11eb-9977-f92470b8d876.png)

captureFeedbackReason

![image](https://user-images.githubusercontent.com/24246902/110421125-de81ee80-80c2-11eb-9f05-10fa6d75325e.png)


Getting the below responses for each step

**askForFeedBack**

```
{ type: 'message',
  text:
   'How would you rate your experience with 5 being Excellent and 1 being Poor. Please provide a number rating.​',
  suggestedActions: { actions: [ [Object] ], to: [] },
  inputHint: 'expectingInput',
  channelId: 'directline',
  locale: 'en-US',
  serviceUrl: 'https://directline.botframework.com/',
  conversation: { id: 'KpcmEeNcPBHLcEgPVU4suC-f' },
  from: { id: 'XXXXX-BOT-D@vLojGrm-9k4', name: 'XXX-DEV' },
  recipient:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a462',
     name: '',
     role: 'user' },
  replyToId: 'KpcmEeNcPBHLcEgPVU4suC-f|0000002',
  speak:
   'How would you rate your experience with 5 being Excellent and 1 being Poor. Please provide a number rating.​',
  id: 'KpcmEeNcPBHLcEgPVU4suC-f|0000003' }
```
**captureFeedBack**

```
{ type: 'message',
  text:
   'How did I do? Your feedback will help me provide better experience. Please provide your feedback below.',
  suggestedActions: { actions: [ [Object] ], to: [] },
  inputHint: 'expectingInput',
  channelId: 'directline',
  locale: 'en-US',
  serviceUrl: 'https://directline.botframework.com/',
  conversation: { id: 'KpcmEeNcPBHLcEgPVU4suC-f' },
  from: { id: 'XXXXX-BOT-D@vLojGrm-9k4', name: 'XXX-DEV' },
  recipient:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a462',
     name: '',
     role: 'user' },
  replyToId: 'KpcmEeNcPBHLcEgPVU4suC-f|0000004',
  speak:
   'How did I do? Your feedback will help me provide better experience. Please provide your feedback below.',
  id: 'KpcmEeNcPBHLcEgPVU4suC-f|0000005' }
```
captureFeedbackReason

```
{ type: 'message',
  text: 'Thank you for your feedback!',
  channelId: 'directline',
  locale: 'en-US',
  serviceUrl: 'https://directline.botframework.com/',
  conversation: { id: 'KpcmEeNcPBHLcEgPVU4suC-f' },
  from: { id: 'XXXXX-BOT-D@vLojGrm-9k4', name: 'XXXX-DEV' },
  recipient:
   { id: 'dl_7cd3a405-b078-471b-a85e-b1ebb116a462',
     name: '',
     role: 'user' },
  replyToId: 'KpcmEeNcPBHLcEgPVU4suC-f|0000006',
  speak: 'Thank you for your feedback!',
  id: 'KpcmEeNcPBHLcEgPVU4suC-f|0000007' }
```

But, getting the same error message on every step. The error is coming without suggested action also.


Thanks
.Sreekanth

**Comment by mdrichardson** [comment]
I don't see anything that I can point to for sure, but a couple of things jump out.

1. Can you include the code for `Feeback.responder.renderTemplate()` and `this.getStateFromAccessor()`?
2. `this.feedbackstate` is a big red flag. All dialogs are singletons, so all users are going to share `this.feedbackstate` and you're going to have big concurrency issues. I lean towards this being the problem, but am not completely sure.
3. What version of `botbuilder-azure` are you on? Alternatively, you may want to try [`BlobsTranscriptStore`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts)
4. In `askForFeedBack()` and `captureFeedBack()`, you have `if (prompt)`, but if there's no prompt, it still returns `step.prompt...`

**Comment by YammanureSreekanth** [comment]
@mdrichardson,

1. Can you include the code for Feeback.responder.renderTemplate() and this.getStateFromAccessor()?

renderTemplate
```
public async renderTemplate(turnContext: TurnContext,
        templateId: string,
        // tslint:disable-next-line:no-any
        language?: string, data?: any): Promise<Activity | undefined> {
        const fallbackLocales: string[] = this.languageFallback;

        if (language !== undefined) {
            fallbackLocales.push(language);
        }

        fallbackLocales.push('default');

        // try each locale until successful
        for (const locale of fallbackLocales) {
            for (const renderer of this.templateRenders) {
                // tslint:disable-next-line:no-any
                const templateOutput: any = await renderer.renderTemplate(turnContext, locale, templateId, data);
                if (templateOutput) {
                    if (typeof templateOutput === 'string' || templateOutput instanceof String) {
                        const def: Partial <Activity> = { type: ActivityTypes.Message, text: <string> templateOutput};

                        return  <Activity> def;
                    } else {
                        return <Activity>templateOutput;
                    }
                }
            }
        }

        return undefined;
    }

```

getStateFromAccessor

```
private async getStateFromAccessor(context: TurnContext): Promise<IFeedbackState>  {
        const state: IFeedbackState | undefined = await this.feedbackStateAccessor.get(context);
        if (state === undefined) {
            const userNewState: IUserProfileFeedback = {
                id: '',
                name: '',
                email: ''
            };
            const newState: IFeedbackState = {
                userProfile: userNewState,
                conversationDate: new Date(),
                rating: 0,
                reason: ''
            };
            await this.feedbackStateAccessor.set(context, newState);

            return newState;
        }

        return state;
    }
```
2. this.feedbackstate is a big red flag. All dialogs are static, so all users are going to share this.feedbackstate and you're going to have big concurrency issues. I lean towards this being the problem, but am not completely sure.

feedbackstate is coming from the user state only. So it will not be for all users.

3. What version of botbuilder-azure are you on? Alternatively, you may want to try BlobsTranscriptStore

botbuilder-azure is "botbuilder-azure": "^4.11.0".  But didn't find **BlobsTranscriptStore** this in botbuilder-azure. Please let me know in which module it's present. Tried to use from 'botbuilder' and 'botbuilder-azure' but didn't find it.


4. In askForFeedBack() and captureFeedBack(), you have if (prompt), but if there's no prompt, it still returns step.prompt...

Will provide details ASAP.

**Comment by mdrichardson** [comment]
I think `renderTemplate` and `getStateFromAccessor` are probably fine.

> feedbackstate is coming from the user state only. So it will not be for all users.

In `captureFeedBack()`, you set `this.feedbackstate` from the userstate, yes. But again, `this.feedbackstate` is a static variable, so it's shared by all users. Let me give you an example of what can happen.

1. User A enters `captureFeedBack()` with `step.result` equal to `99`
2. `this.feedbackstate.rating` is set to `99` 3 lines later
3. User B enters `captureFeedBackReason()` with `step.result` not equal to `-1`, so `this.feedbackstate` then becomes set by User B's `step.context`
4. User A continues through `captureFeedBack()` and hits `await this.feedbackStateAccessor.set(step.context, this.feedbackstate)`. Well, `this.feedbackstate` was just set by User B, but now it's being save to User A.

Again, all dialogs are singletons, so this is definitely going to cause concurrency issues.

`BlobsTranscriptStore` is in [`botbuilder-azure-blobs`](https://www.npmjs.com/package/botbuilder-azure-blobs)

**Comment by YammanureSreekanth** [comment]
@mdrichardson - Sorry for the late reply. I'll reply back soon.

**Comment by YammanureSreekanth** [comment]
@mdrichardson -  Could you please change the status to Open

**Comment by mdrichardson** [comment]
@SreekanthOAuth Did you have an update for this?

**Comment by YammanureSreekanth** [comment]
@mdrichardson - Thanks for reopening it.

I would give the update tomorrow EOD IST.

**Comment by mdrichardson** [comment]
@SreekanthOAuth I haven't seen an update from you, so I'll close this issue. When you have the requested information and have made the changes related to the dialogs being singletons, please open a new issue.

**Comment by YammanureSreekanth** [comment]
@mdrichardson - I'm really sorry for the late reply.

Created a new issue for the same - https://github.com/microsoft/botframework-solutions/issues/3797.

Thank you.
