### ISSUE TITLE
Knowledgebase is not getting created through Virtual Assistant template PowerShell script

### ISSUE THREAD

**Issue by pravinambekar** [microsoft/botframework-solutions#3848]
#### What project is affected?
The QnAMaker based azure chatbot.

#### What language is this in?
Code for web app bot is written in c# and deployment  is done using PowerShell script

#### What happens?
I am trying to deploy resources for Azure Web App bot, this is being done with help of Virtual Assistant Template,
The issue is when i am trying to execute PowerShell script (deploy.ps1) is does not create knowledgebase.
I can see related services are being created in azure (f.x Azure Cognitive service, search service, app service), but it is failing in PowerShell when it comes to creating knowledgebase.
Surprisingly similar set up successfully ran last time a few months ago, under different resource group, but now it is throwing error as shown in below screen shot.
![image](https://user-images.githubusercontent.com/41193836/142979028-329fe100-61da-4cae-8e44-8cb5e45be0e1.png)

#### What are the steps to reproduce this issue?
1) Getting the VA template provided by Microsoft Bot framework
2) Customizing and configuring resources and template in the solution
3) Logging to Azure account through PowerShell 
4) Setting up correct subscription and then executing deploy.ps1 script for provisioning resources

#### What were you expecting to happen?
That all the mentioned services get created and knowledgebase also get created with help of .qna files defined during execution.

#### Can you share any logs, error output, etc.?
As shared above the PowerShell console throws error while creating KB and the log file from cognitivemodel.ps1 says :
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\@microsoft\botframework-cli\bin\run'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

Even after installing BotFramework-cli and the error in cognitive log file says: 
**Cannot find module 'C:\Users\XXX\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\bin\run**

#### Any screenshots or additional context?
Additional context would be that, the BotFramework module is already installed and i am afraid that either bot framework cli is not correctly working or have some issue in creating kb during script execution

Hello @lauren-mills   Any suggestion greatly appreciated 
as surprisingly for earlier it worked without any error, the procedure for provisioning resources through VA template is same.
https://github.com/microsoft/botframework-solutions/issues/3779  is for reference

**Comment by lauren-mills** [comment]
@pravinambekar, can you try uninstalling the bf CLI using `npm uninstall @microsoft/botframework-cli -g`, then reinstalling with `npm i @microsoft/botframework-cli -g`? Looks like something is wrong with your CLI installation

**Comment by pravinambekar** [comment]
> @pravinambekar, can you try uninstalling the bf CLI using `npm uninstall @microsoft/botframework-cli -g`, then reinstalling with `npm i @microsoft/botframework-cli -g`? Looks like something is wrong with your CLI installation

Hello @lauren-mills , Hello @mrivera-ms ,
As suggested  I have re installed bot framework CLI and botskills package, the earlier error seems to have gone but i am still not able to create KB , giving same error (can be seen in the screen shot below)
![image](https://user-images.githubusercontent.com/41193836/144822433-65e01232-10e7-439e-a444-cb885c82cb91.png)

I have also checked deployment log files and no error recorded in the log information
![image](https://user-images.githubusercontent.com/41193836/144822730-8c169eca-b4fe-41dc-89d1-23f98bda5eed.png)

You can see below screenshot just to confirm that services are getting created correctly 
![image](https://user-images.githubusercontent.com/41193836/144823002-3c0680e1-3572-46a0-a8db-183cd8367467.png)

I really failed to understand why KB is not getting created although same set up worked earlier under same subscription,
on top of that there is no trace to check what causing the error.
PS: the current version for qnamaker service being used is : **cognitiveservices.azure.com/qnamaker/v5.0-preview.2**  and app service plan is on Linux kind (same as earlier)
Any help is highly appreciated .

**Comment by lauren-mills** [comment]
Just to confirm, there's nothing in your update_cognitive_models_log.txt file right?

Also, can you send the command you're using with any names/keys redacted?

**Comment by pravinambekar** [comment]
> Just to confirm, there's nothing in your update_cognitive_models_log.txt file right?
> 
> Also, can you send the command you're using with any names/keys redacted?

No, Just the message: AZ CLI passes minimum version. Current version is 2.19.1

**Comment by pravinambekar** [comment]
> Just to confirm, there's nothing in your update_cognitive_models_log.txt file right?
> 
> Also, can you send the command you're using with any names/keys redacted?

Hello @lauren-mills 

Apparently there was no update_cognitive_models_log.txt exist in the folder, i have even created new VA template but it was not there too,
I manually have tried creating file with this name, but no log recorded.

Talking about commands i edited / customized are mostly about LUIS, COSMOS DB
I have customized template to skip LUIS and cosmos DB configuration , and necessary script block has been commented.

**Comment by lauren-mills** [comment]
Apologies, I meant to ask for the deploy_cognitive_models_log.txt.

Also, if you've removed the Luis setup that maybe causing you some issues with the dispatch model, since it is a Luis model underneath.

Can you check that log file above, and also send your modified scripts for me to take a look at?

**Comment by pravinambekar** [comment]
> Apologies, I meant to ask for the deploy_cognitive_models_log.txt.
> 
> Also, if you've removed the Luis setup that maybe causing you some issues with the dispatch model, since it is a Luis model underneath.
> 
> Can you check that log file above, and also send your modified scripts for me to take a look at?

Hello @lauren-mills ,

Yes, have attached deploy ps script and also template for your reference, i also have checked deploy cognitive log file and it has nothing as such

Hope this helps you to understand what's wrong with script and/or template,
Few things just in case you need:
1) I am using $qnaEndpoint = "https://westus.api.cognitive.microsoft.com/qnamaker/v5.0-preview.2" in deploy script
2) An additional service has been added in the template for an angular application along with bot services (just not to confuse with other services)
3) LUIS part in template and in deploy ps script has commented 
4) COSMOS db create is disabled.
5) .qna files are being used for kb creation (same as standard VA template, no change in the files)
6) Deployment procedure is same as mentioned in document : https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources/ 

Let me know if any additional information is required to reproduce the issue.

Thank you.

[deploy.txt](https://github.com/microsoft/botframework-solutions/files/7673734/deploy.txt)
[template.txt](https://github.com/microsoft/botframework-solutions/files/7673735/template.txt)

**Comment by pravinambekar** [comment]
> > Apologies, I meant to ask for the deploy_cognitive_models_log.txt.
> > Also, if you've removed the Luis setup that maybe causing you some issues with the dispatch model, since it is a Luis model underneath.
> > Can you check that log file above, and also send your modified scripts for me to take a look at?
> 
> Hello @lauren-mills ,
> 
> Yes, have attached deploy ps script and also template for your reference, i also have checked deploy cognitive log file and it has nothing as such
> 
> Hope this helps you to understand what's wrong with script and/or template, Few things just in case you need:
> 
> 1. I am using $qnaEndpoint = "https://westus.api.cognitive.microsoft.com/qnamaker/v5.0-preview.2" in deploy script
> 2. An additional service has been added in the template for an angular application along with bot services (just not to confuse with other services)
> 3. LUIS part in template and in deploy ps script has commented
> 4. COSMOS db create is disabled.
> 5. .qna files are being used for kb creation (same as standard VA template, no change in the files)
> 6. Deployment procedure is same as mentioned in document : https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources/
> 
> Let me know if any additional information is required to reproduce the issue.
> 
> Thank you.
> 
> [deploy.txt](https://github.com/microsoft/botframework-solutions/files/7673734/deploy.txt) [template.txt](https://github.com/microsoft/botframework-solutions/files/7673735/template.txt)

Update: I was just checking all the services created and tried to create KB manually in qnamaker portal, though it is also giving same **No Endpoint keys found** error, i am afraid that the script executed to provision resources might have some mis-configuration related to cognitive service endpoint, and in console it returns **401 saying Access denied due to invalid subscription key or wrong API endpoint in qnamaker portal browser console**
just a thought , but it is what it was earlier, so unable to trace down further.

**Comment by lauren-mills** [comment]
Hi @pravinambekar, after looking into this, you are no longer able to create *new* qna maker services that use the v5.0-preview. Only existing QnA Services made with the preview flag continue working. So you will not be able to use the VA scripts to create a qna service with the 5.0 preview features.

Qna Maker has been combined with other cognitive services in a single Azure resource going forward. If you want to migrate to that solution to utilize whatever features you are looking for from Qna Maker beyond what is currently supported in QnA v4.0 used in VA, you will need to make those changes yourself. The Virtual Assistant template and solution will not be receiving future updates to support this due to our focus on other product areas. 

If you would like to read more about the new direction of QnA Maker, here is their team's new documentation: https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/overview

**Comment by munozemilio** [comment]
Closing this due to inactivity. @pravinambekar feel free to reopen if the issue is not solved.
