### ISSUE TITLE
Enterprise Bot Template cannot configure AppInsights TelemetryClient

### ISSUE THREAD

**Issue by ctstone** [microsoft/botframework-solutions#842]
**Project**
Enterprise Bot Template

**Description**
When following the [guide](https://github.com/Microsoft/AI/tree/master/templates/Enterprise-Template/src/typescript/enterprise-bot) for Enterprise Bot TS template, and running `npm start`, the app crashes with

```js
Error: Instrumentation key not found, pass the key in the config to this method or set the key in the environment variable APPINSIGHTS_INSTRUMENTATIONKEY before starting the server
    at Function.Config._getInstrumentationKey (/my-bot/node_modules/applicationinsights/out/Library/Config.js:47:19)
    at new Config (/my-bot/node_modules/applicationinsights/out/Library/Config.js:7:64)
    at NodeClient.TelemetryClient (/my-bot/node_modules/applicationinsights/out/Library/TelemetryClient.js:24:22)
    at new NodeClient (/my-bot/node_modules/applicationinsights/out/Library/NodeClient.js:25:42)
    at Object.<anonymous> (/my-bot/lib/index.js:56:26)
```

**To Reproduce**
1. Follow the linked guide
1. Start the bot

**Expected behavior**
The bot should start successfully. The bot already knows the name of my AppInsights instance (`APPINSIGHTS_NAME` from`.env.development`) and the value of my instrumentation key (stored in my .bot file), so it should be able to configure the telemetry client without any extra info from the user.

**Additional context**
Using yeoman template from branch `master 5f423895`

**Comment by ctstone** [comment]
This might be related to #841 (see workaround there)
