### ISSUE TITLE
Enterprise Bot Template points to non-existent i18n resource

### ISSUE THREAD

**Issue by ctstone** [microsoft/botframework-solutions#843]
**Project**
Enterprise Bot Template

**Description**
When starting a new bot created with the yeoman template, it crashes when the Emulator connects:

```js
{ Error: Cannot find module './resources/Intro.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at Module.patchedRequire [as require] (/my-bot/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.buildIntroCard (/my-bot/lib/dialogs/main/mainResponses.js:18:27)
    at MainResponses.responseTemplates.Map (/my-bot/lib/dialogs/main/mainResponses.js:95:50)
    at DictionaryRenderer.renderTemplate (/my-bot/lib/dialogs/templateManager/dictionaryRenderer.js:28:32)
    at MainResponses.renderTemplate (/my-bot/lib/dialogs/templateManager/templateManager.js:60:55)
    at MainResponses.replyWith (/my-bot/lib/dialogs/templateManager/templateManager.js:41:42) code: 'MODULE_NOT_FOUND' }
```

**To Reproduce**
1. Create a new enterprise bot using yeoman
1. Create the required services using msbot
1. Configure the .env.development
1. npm start
1. Open the .bot file using BF Emulator

**Expected behavior**
The Emulator connects successfully

**Additional context**
I poked around the en.json config, and it includes the property `"introPath": "./resources/Intro.json"`, however this file does not exist in the template

Template was creating from yeoman generator associated with git branch `master 5f423895`

**Comment by ctstone** [comment]
This is a problem with the `copy-files` npm script, which is not finding the json files under `src/dialogs/main/resources/`

Current behavior (with --verbose added):

```
copyfiles --verbose --up 1 ./src/**/*.json ./lib

unglobed path: ./src/locales/de.json
unglobed path: ./src/locales/en.json
unglobed path: ./src/locales/es.json
copy from: ./src/locales/de.json
copy to: lib/locales/de.json
unglobed path: ./src/locales/fr.json
unglobed path: ./src/locales/it.json
unglobed path: ./src/locales/zh.json
copy from: ./src/locales/en.json
copy to: lib/locales/en.json
copy from: ./src/locales/es.json
copy to: lib/locales/es.json
copy from: ./src/locales/fr.json
copy to: lib/locales/fr.json
copy from: ./src/locales/it.json
copy to: lib/locales/it.json
copy from: ./src/locales/zh.json
copy to: lib/locales/zh.json
```

And here is the result after changing the glob:

```
> copyfiles --verbose --up 1 ./src/**/**/*.json ./lib

unglobed path: ./src/dialogs/main/resources/Intro.de.json
unglobed path: ./src/dialogs/main/resources/Intro.es.json
unglobed path: ./src/dialogs/main/resources/Intro.fr.json
unglobed path: ./src/dialogs/main/resources/Intro.it.json
unglobed path: ./src/dialogs/main/resources/Intro.json
unglobed path: ./src/dialogs/main/resources/Intro.zh.json
unglobed path: ./src/locales/de.json
unglobed path: ./src/locales/en.json
unglobed path: ./src/locales/es.json
unglobed path: ./src/locales/fr.json
unglobed path: ./src/locales/it.json
unglobed path: ./src/locales/zh.json
copy from: ./src/dialogs/main/resources/Intro.de.json
copy to: lib/dialogs/main/resources/Intro.de.json
copy from: ./src/dialogs/main/resources/Intro.es.json
copy to: lib/dialogs/main/resources/Intro.es.json
copy from: ./src/dialogs/main/resources/Intro.fr.json
copy to: lib/dialogs/main/resources/Intro.fr.json
copy from: ./src/dialogs/main/resources/Intro.it.json
copy to: lib/dialogs/main/resources/Intro.it.json
copy from: ./src/dialogs/main/resources/Intro.json
copy to: lib/dialogs/main/resources/Intro.json
copy from: ./src/dialogs/main/resources/Intro.zh.json
copy to: lib/dialogs/main/resources/Intro.zh.json
copy from: ./src/locales/de.json
copy to: lib/locales/de.json
copy from: ./src/locales/en.json
copy to: lib/locales/en.json
copy from: ./src/locales/es.json
copy to: lib/locales/es.json
copy from: ./src/locales/fr.json
copy to: lib/locales/fr.json
copy from: ./src/locales/it.json
copy to: lib/locales/it.json
copy from: ./src/locales/zh.json
copy to: lib/locales/zh.json
```

**Comment by dfavretto** [comment]
Hi @ctstone , thanks for your contribution!
We tried executing this same command and it worked fine for us.

![image](https://user-images.githubusercontent.com/23645105/53198427-24aea700-35fb-11e9-8fac-8b5145580698.png)

However, we've been researching and found that there are some differences in the behavior of `copyfiles` between different Operative Systems; could you confirm us if you are using an OS that's not Windows?

**Comment by ctstone** [comment]
You are correct! I am currently using macOS 10.14.3

**Comment by ctstone** [comment]
BTW, TS can import JSON natively: https://devblogs.microsoft.com/typescript/announcing-typescript-2-9-2/#json-imports

Though I realize you are probably depending on the upstream module to do the actual import/require.
